Repository OpenSlides/openslides-backend, pull requests merged in 2021-12, with the labels that each got.

#1077 Make health routes public
  .github/workflows/continuous_integration.yml
  README.md
  openslides_backend/http/views/action_view.py
  openslides_backend/http/views/presenter_view.py
  tests/system/action/test_general.py
Labels: feature

#1076 Update migration route & restructure requirements
  .github/workflows/continuous_integration.yml
  Dockerfile
  Makefile
  dev/.bashrc
  dev/Dockerfile.dev
  dev/bashrc
  dev/dc.local-ds.yml
  migrations/Dockerfile
  migrations/__init__.py
  migrations/docker-compose.yml
  migrations/migrate.py
  migrations/tests/test_0008_remove_field_dont_set_identifier.py
  migrations/tests/test_with_sql_dump.py
  openslides_backend/http/views/action_view.py
  openslides_backend/main.py
  openslides_backend/migrations/__init__.py
  openslides_backend/migrations/migration_handler.py
  requirements/partial/requirements_datastore_as_package.txt
  requirements/partial/requirements_datastore_locally.txt
  requirements/partial/requirements_development.txt
  requirements/partial/requirements_production.txt
  requirements/requirements_development.txt
  requirements/requirements_development_local_ds.txt
  requirements/requirements_migrations.txt
  requirements/requirements_production.txt
  tests/system/action/organization/test_initial_import.py
Labels: clean up, feature

#1089 Improve the performance of vote.create by getting the ids for create in bulk.
  openslides_backend/action/action.py
  openslides_backend/action/generics/create.py
Labels: bug, high

#1098 Rename subfolder migrations
  openslides_backend/http/views/action_view.py
  openslides_backend/migration_handler/__init__.py
  openslides_backend/migration_handler/migration_handler.py
Labels: bug, blocker

#1095 Allow poll.anonymize in state 'published'.
  openslides_backend/action/actions/poll/anonymize.py
  tests/system/action/poll/test_anonymize.py
Labels: bug

#1104 Update dependencies
  .github/workflows/continuous_integration.yml
  Dockerfile
  README.md
  dev/Dockerfile.dev
  migrations/Dockerfile
  openslides_backend/environment.py
  openslides_backend/presenter/presenter_interface.py
  openslides_backend/services/datastore/commands.py
  openslides_backend/services/datastore/interface.py
  openslides_backend/services/media/interface.py
  openslides_backend/shared/interfaces/wsgi.py
  requirements/export_datastore_commit.sh
  requirements/partial/requirements_datastore_as_package.txt
  requirements/partial/requirements_datastore_locally.txt
  requirements/partial/requirements_development.txt
  requirements/partial/requirements_production.txt
Labels: dependencies

#1106 Update datastore
  .github/docker-compose/docker-compose.prod.yml
  .github/workflows/continuous_integration.yml
  Dockerfile
  Makefile
  dev/Dockerfile.dev
  dev/docker-compose.dev.yml
  dev/entrypoint.sh
  dev/run-tests.sh
  entrypoint.sh
  migrations/Dockerfile
  migrations/entrypoint.sh
  migrations/wait.sh
  requirements/export_datastore_commit.sh
  scripts/export_datastore_variables.sh
  scripts/wait.sh
Labels: dependencies, blocker

#1084 Fix `projection.delete` for cascade deletions
  openslides_backend/action/action.py
  openslides_backend/action/actions/projection/delete.py
  openslides_backend/action/relations/meeting_user_ids_handler.py
  tests/system/action/meeting/test_archive.py
  tests/system/action/meeting/test_delete.py
  tests/system/action/test_archived_meeting.py
  tests/system/base.py
Labels: bug

#1114 Copy mounted folders
  dev/Dockerfile.dev
Labels: bug, blocker
