Repository OpenSlides/openslides-backend, pull requests merged in 2022-12, with the labels that each got.

#1557 Remove ostcar from issue template
  .github/workflows/announce-file-changes-template.md
Labels: documentation

#1560 Possible fix for defaultdict in response body.
  openslides_backend/presenter/search_users_by_name_or_email.py
Labels: bug

#1559 Add a fix to the decimal validation code in checker.
  openslides_backend/models/checker.py
  tests/system/action/meeting/test_import.py
Labels: bug

#1495 Issue1461 vote interface changed
  .github/workflows/continuous_integration.yml
  cli/generate_models.py
  dev/Dockerfile.dev
  dev/docker-compose.dev.yml
  dev/generate_vote_main_key.py
  dev/vote_decrypt/public_vote_main_key
  dev/vote_decrypt/vote_main_key
  openslides_backend/action/actions/poll/mixins.py
  openslides_backend/action/actions/poll/reset.py
  openslides_backend/action/actions/poll/start.py
  openslides_backend/action/actions/poll/stop.py
  openslides_backend/action/actions/vote/user_token_helper.py
  openslides_backend/models/models.py
  openslides_backend/services/datastore/extended_adapter.py
  openslides_backend/services/datastore/interface.py
  openslides_backend/services/vote/adapter.py
  openslides_backend/services/vote/interface.py
  requirements/partial/requirements_development.txt
  tests/system/action/poll/poll_test_mixin.py
  tests/system/action/poll/test_publish.py
  tests/system/action/poll/test_reset.py
  tests/system/action/poll/test_start.py
  tests/system/action/poll/test_stop.py
  tests/system/action/poll/test_vote.py
  tests/system/base.py
  tests/system/util.py
Labels: feature

#1556 Bugfix: database error as string not handled
  openslides_backend/services/datastore/handle_datastore_errors.py
Labels: bug

#1565 ds issue222 migration meeting.import need UpdateEvent
  openslides_backend/action/actions/meeting/import_.py
Labels: high
