Repository OpenSlides/openslides-backend, pull requests merged in 2022-06, with the labels that each got.

#1349 Issue1348 raise error on None-value for vote_delegations_$_from
  openslides_backend/action/actions/user/user_mixin.py
  tests/system/action/user/test_update_delegation.py
Labels: bug

#1331 Draft Version of the meeting.import merge users feature.
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_import.py
Labels: high, feature

#1273 Opentelemetry
  README.md
  openslides_backend/action/action.py
  openslides_backend/action/action_handler.py
  openslides_backend/http/views/base_view.py
  openslides_backend/main.py
  openslides_backend/shared/env.py
  openslides_backend/shared/interfaces/env.py
  openslides_backend/shared/otel.py
  requirements/partial/requirements_datastore_locally.txt
  requirements/partial/requirements_production.txt
  setup.cfg
  tests/system/action/base.py
  tests/unit/test_user_scopes.py
Labels: performance

#1354 Remove publish_immediately from write req. of poll and option
  global/data/example-data.json
  global/data/initial-data.json
  migrations/migrations/0027_remove_publish_immediately.py
  migrations/migrations/0028_rename_motion_sort_children_ids.py
  migrations/tests/test_0027_remove_publish_immediately.py
  migrations/tests/test_0028_rename_motion_sort_children_ids.py
  openslides_backend/action/action.py
  openslides_backend/action/action_handler.py
  openslides_backend/action/actions/motion/sort.py
  openslides_backend/action/actions/option/update.py
  openslides_backend/action/actions/poll/create.py
  openslides_backend/action/actions/poll/update.py
  openslides_backend/action/actions/user/send_invitation_email.py
  tests/system/action/motion/test_sort.py
  tests/system/action/option/test_update.py
  tests/system/action/poll/test_create.py
  tests/system/action/poll/test_update.py
  tests/system/action/test_permissions.py
Labels: bug, high

#1364 #1363 Remove unneccessary locked_fields, some improvements
  openslides_backend/action/actions/poll/mixins.py
  openslides_backend/action/actions/poll/stop.py
  openslides_backend/action/actions/vote/create.py
  openslides_backend/services/datastore/extended_adapter.py
  tests/system/action/poll/poll_test_mixin.py
  tests/system/action/poll/test_stop.py
Labels: critical

#1370 Fix problem with user/meeting_ids of merged users in meeting.import.
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_import.py
Labels: bug, high

#1376 Add unique check to motion_comment.create
  openslides_backend/action/actions/motion_comment/create_delete_update.py
  tests/system/action/motion_comment/test_create.py
Labels: bug

#1380 Fix deletion of motion in projector history
  openslides_backend/action/actions/projection/delete.py
  tests/system/action/projection/test_delete.py
Labels: bug, high

#1381 Issue1378 set_as_template for meeting.clone
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_clone.py
Labels: high, feature

#1384 use local datastore for writer including debug
  dev/Dockerfile.dev
  dev/dc.local-ds.yml
Labels: feature

#1375 Cleanup of the clone meeting code.
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/models/checker.py
  tests/system/action/meeting/test_clone.py
Labels: clean up

#1385 Update assignees in template
  .github/workflows/announce-file-changes-template.md
Labels: high
