Repository OpenSlides/openslides-backend, pull requests merged in 2022-07, with the labels that each got.

#1388 Validate all write request fields
  openslides_backend/action/action.py
  openslides_backend/action/action_handler.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/models/fields.py
  tests/system/action/projector/test_update.py
  tests/system/base.py
Labels: feature, tests

#1391 Mediafile: Update title, parent unique check, add owner_id in meeting case.
  openslides_backend/action/actions/mediafile/mixins.py
  tests/system/action/mediafile/test_create_directory.py
Labels: bug, high

#1394 Change permission for forwarding meeting presenter
  openslides_backend/presenter/get_forwarding_meetings.py
Labels: bug, high

#1395 Issue1393 meeting.clone user in 2 meetings
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/models/checker.py
  openslides_backend/presenter/export_meeting.py
  tests/system/action/meeting/test_clone.py
  tests/system/presenter/test_export_meeting.py
Labels: bug, high

#1398 Issue1396 Remove forbidden fields to allow import of exported data
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
Labels: bug

#1397 Add checks to migration tests
  openslides_backend/models/checker.py
  tests/system/migrations/conftest.py
  tests/system/migrations/test_0010_add_sequential_numbers.py
  tests/system/migrations/test_0011_rename_used_as_list_of_speaker_countdown_meeting_id.py
  tests/system/migrations/test_0012_committee_user_relation.py
  tests/system/migrations/test_0019_calc_mediafile_is_public.py
  tests/system/migrations/test_0020_2nd_migration_seq_numbers.py
  tests/system/migrations/test_0028_rename_motion_sort_children_ids.py
Labels: high, tests

#1399 Add replacement_enum to font_$_id and logo_$_id
  global/meta/models.yml
  openslides_backend/action/actions/meeting/base_set_mediafile_action.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_set_font.py
  tests/system/action/meeting/test_set_logo.py
  tests/system/action/meeting/test_unset_font.py
Labels: feature

#1407 Fix datastore commit
  requirements/export_datastore_commit.sh
  requirements/partial/requirements_datastore_locally.txt
  requirements/partial/requirements_production.txt
Labels: bug, clean up

#1410 Add ex-users to export_meeting, add test, update clone.
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/export_helper.py
  tests/system/action/meeting/test_clone.py
  tests/system/presenter/test_export_meeting.py
Labels: bug, high

#1412 User with manager perms can change to all states.
  openslides_backend/action/actions/motion/follow_recommendation.py
  openslides_backend/action/actions/motion/set_state.py
  tests/system/action/motion/test_set_state.py
Labels: high, feature

#1416 Issue1137 new collection action_worker in models.yml
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: feature

#1415 Add check_database presenter. Add tests.
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/check_database.py
  tests/system/presenter/test_check_database.py
Labels: feature
