Repository OpenSlides/openslides-backend, pull requests merged in 2022-02, with the labels that each got.

#1188 Issue1181 Fix migration errors in update-event
  migrations/migrations/0012_committee_user_relation.py
  migrations/tests/test_0012_committee_user_relation.py
Labels: critical

#1164 Issue1150 Use execute_action_internally
  openslides_backend/action/action.py
  openslides_backend/action/actions/assignment_candidate/delete.py
  openslides_backend/action/actions/projection/delete.py
  openslides_backend/action/actions/projector/delete.py
  openslides_backend/action/actions/projector_countdown/delete.py
  tests/system/action/base.py
  tests/system/action/meeting/test_clone.py
Labels: bug

#1177 Add the archived_meeting_ids to organization.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0013_archived_meeting_ids.py
  migrations/tests/test_0013_archived_meeting_ids.py
  openslides_backend/action/actions/meeting/archive.py
  openslides_backend/action/actions/meeting/unarchive.py
  openslides_backend/models/models.py
  setup.cfg
  tests/system/action/meeting/test_archive.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_unarchive.py
Labels: high, feature

#1195 Rename and modify committee/template_meeting_id.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0014_rename_template_meeting_id.py
  migrations/tests/test_0014_rename_template_meeting_id.py
  openslides_backend/action/actions/committee/update.py
  openslides_backend/models/models.py
  tests/system/action/committee/test_update.py
Labels: feature

#1194 Update the permission check of the committee of meeting.clone.
  openslides_backend/action/actions/meeting/clone.py
  tests/system/action/meeting/test_clone.py
Labels: high

#1186 Allow to delete archived meetings
  openslides_backend/action/mixins/archived_meeting_check_mixin.py
  setup.cfg
  tests/system/action/meeting/test_delete.py
Labels: bug, high

#1209 Fix problem with workflow_id
  global/data/initial-data.json
  migrations/migrations/0015_remove_workflow_id.py
  migrations/tests/test_0015_remove_workflow_id.py
  openslides_backend/action/actions/motion/update.py
Labels: bug, high

#1206 Allow to set gender in user.update_self and add a test.
  openslides_backend/action/actions/user/update_self.py
  tests/system/action/user/test_update_self.py
Labels: bug

#1205 Remove not needed mediafiles from the example data.
  global/data/example-data.json
  tests/system/action/meeting/test_delete.py
Labels: bug

#1207 Add motion_state.sort action and add tests.
  openslides_backend/action/actions/motion_state/__init__.py
  openslides_backend/action/actions/motion_state/sort.py
  tests/system/action/motion_state/test_sort.py
Labels: feature, good first issue

#1208 Update the unique name check of chat_groups.
  openslides_backend/action/actions/chat_group/mixins.py
  tests/system/action/chat_group/test_create.py
Labels: bug, good first issue

#1211 Update user.forget_password to include the orga.url
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0016_remove_url_name_and_users_pdf_url.py
  migrations/tests/test_0016_remove_url_name_and_users_pdf_url.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/organization/update.py
  openslides_backend/action/actions/user/forget_password.py
  openslides_backend/action/actions/user/send_invitation_email.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_update.py
  tests/system/action/organization/test_update.py
  tests/system/action/user/test_forget_password.py
  tests/system/action/user/test_send_invitation_email.py
Labels: high, clean up, good first issue

#1221 Fill entitled_users with all entitled users
  openslides_backend/action/actions/poll/mixins.py
  tests/system/action/poll/test_stop.py
Labels: bug, high

#1223 Add pronoun to permission groups
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  tests/system/action/user/test_update.py
Labels: bug, critical

#1224 Cleanup: Use new format in meeting_export.
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/export_helper.py
Labels: clean up

#1225 Add a function to give a sequential_number in create results too.
  openslides_backend/action/mixins/sequential_numbers_mixin.py
  tests/system/action/assignment/test_create.py
  tests/system/action/topic/test_create.py
Labels: low, feature, good first issue

#1226 Add field weight to group.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0017_add_group_weight.py
  migrations/tests/test_0017_add_group_weight.py
  openslides_backend/action/actions/group/create.py
  openslides_backend/models/models.py
  tests/system/action/group/test_create.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/action/test_action_command_format.py
Labels: low, feature

#1232 Disallow to forward amendments.
  openslides_backend/action/actions/motion/create_forwarded.py
  tests/system/action/motion/test_create_forwarded.py
Labels: feature, good first issue

#1229 Add an export presenter.
  migrations/__init__.py
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/http/views/presenter_view.py
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/export_meeting.py
  tests/system/presenter/test_export_meeting.py
Labels: high, feature

#1219 Add set_as_template to meeting.{create,update}
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0008_remove_field_dont_set_identifier.py
  migrations/migrations/0015_remove_workflow_id.py
  migrations/migrations/0016_remove_url_name_and_users_pdf_url.py
  migrations/migrations/0018_remove_template_meeting_committee_relation.py
  migrations/tests/test_0018_remove_template_meeting_committee_relation.py
  openslides_backend/action/actions/committee/update.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/models/models.py
  requirements/export_datastore_commit.sh
  tests/system/action/committee/test_update.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_update.py
Labels: high
