Repository OpenSlides/openslides-backend, pull requests merged in 2022-09, with the labels that each got.

#1430 Add l10n to the backend. Update forget_password.
  Makefile
  openslides_backend/action/actions/user/forget_password.py
  openslides_backend/http/views/action_view.py
  openslides_backend/locale/backend.pot
  openslides_backend/locale/de_DE/LC_MESSAGES/messages.mo
  openslides_backend/locale/de_DE/LC_MESSAGES/messages.po
  openslides_backend/locale/en_US/LC_MESSAGES/messages.mo
  openslides_backend/locale/en_US/LC_MESSAGES/messages.po
  openslides_backend/locale/translator.py
  requirements/partial/requirements_production.txt
  tests/system/action/base.py
  tests/system/action/poll/test_vote.py
  tests/system/action/user/test_forget_password.py
Labels: feature

#1451 Fix language extraction from client header
  openslides_backend/locale/translator.py
  tests/system/action/user/test_forget_password.py
Labels: bug, critical

#1450 Allow meeting admins to edit higher-OML user's meeting-specific information
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  tests/system/action/user/test_update.py
Labels: high

#1458 Issue1429 meeting.import duplicate users
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/user_mixin.py
  tests/system/action/meeting/test_import.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
Labels: bug, high

#1456 Add organization.user_ids and user.organization_id relation
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/migrations/migrations/0029_update_organization_user_ids.py
  openslides_backend/models/checker.py
  openslides_backend/models/models.py
  tests/system/action/committee/test_create.py
  tests/system/action/committee/test_update.py
  tests/system/action/mediafile/test_create_directory.py
  tests/system/action/mediafile/test_upload.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_update.py
  tests/system/action/organization/test_initial_import.py
  tests/system/action/organization/test_update.py
  tests/system/action/organization_tag/test_create.py
  tests/system/action/test_archived_meeting.py
  tests/system/action/theme/test_create.py
  tests/system/base.py
  tests/system/migrations/test_0029_update_organization_user_ids.py
  tests/system/presenter/test_check_database.py
  tests/system/presenter/test_get_history_information.py
Labels: high

#1432 Small fix to the committee ml handling.
  openslides_backend/presenter/get_user_related_models.py
  tests/system/presenter/test_get_user_related_models.py
Labels: bug

#1434 Fix to KeyError of the mediafile.upload. Add test.
  openslides_backend/action/actions/mediafile/upload.py
  tests/system/action/mediafile/test_upload.py
Labels: bug

#1457 Remove meeting/users_sort_by
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/migrations/migrations/0030_remove_meeting_users_sort_by.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/migrations/test_0030_remove_meeting_users_sort_by.py
  tests/system/presenter/test_check_database.py
Labels: clean up

#1464 Add migration to remove permission 'user.can_see_extra_data'.
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/migrations/migrations/0031_remove_permission_user_can_see_extra_data.py
  tests/system/migrations/test_0031_remove_permission_user_can_see_extra_data.py
Labels: bug, migration

#1471 Add meeting_id logic to check_database presenter.
  openslides_backend/presenter/check_database.py
  tests/system/presenter/test_check_database.py
Labels: high, feature

#1470 Prevent motion poll creation if state doesn't allow it.
  openslides_backend/action/actions/poll/create.py
  tests/system/action/poll/test_create.py
Labels: bug

#1472 Create relation between all_origin_ids and all_derived_motion_ids for motions
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/motion/__init__.py
  openslides_backend/action/actions/motion/create_forwarded.py
  openslides_backend/action/actions/motion/update_all_derived_motion_ids.py
  openslides_backend/migrations/migrations/0032_fix_motion_origin_relations.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_import.py
  tests/system/action/motion/test_create_forwarded.py
  tests/system/migrations/test_0032_fix_motion_origin_relations.py
Labels: high, migration

#1476 Remove agenda fields from other models
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/migrations/migrations/0033_remove_agenda_fields_from_other_models.py
  tests/system/migrations/test_0033_remove_agenda_fields_from_other_models.py
Labels: bug, high, migration

#1482 Don't send vote internal error messages to client.
  openslides_backend/services/vote/adapter.py
Labels: bug

#1480 Fix broken migrations
  openslides_backend/migrations/migrations/0029_update_organization_user_ids.py
  tests/system/migrations/test_0029_update_organization_user_ids.py
  tests/system/migrations/test_0032_fix_motion_origin_relations.py
Labels: bug, high, migration

#1484 migration 0032 with changing updateEvents
  openslides_backend/migrations/migrations/0032_fix_motion_origin_relations.py
  tests/system/migrations/test_0032_fix_motion_origin_relations.py
Labels: high, migration

#1485 Issue1472 Fix multi-forwarding migration error
  openslides_backend/migrations/migrations/0032_fix_motion_origin_relations.py
  tests/system/migrations/test_0032_fix_motion_origin_relations.py
Labels: high, migration

#1481 Prevent to delete yourself.
  openslides_backend/action/actions/user/delete.py
  tests/system/action/user/test_delete.py
Labels: feature

#1479 Add organization.delete_history_information action
  openslides_backend/action/actions/organization/__init__.py
  openslides_backend/action/actions/organization/delete_history_information.py
  openslides_backend/services/datastore/adapter.py
  openslides_backend/services/datastore/commands.py
  openslides_backend/services/datastore/http_engine.py
  openslides_backend/services/datastore/interface.py
  tests/system/action/organization/test_delete_history_information.py
Labels: high, feature

#1487 vote-service: shorter fieldnames for new crypt-fields in poll
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: feature

#1490 Remove allow_forwarding from default states
  openslides_backend/action/actions/motion_workflow/create.py
Labels: high, clean up

#1492 Update checker: check replacement_enum
  openslides_backend/models/checker.py
  tests/system/action/meeting/test_import.py
Labels: bug, high

#1493 Issue1461 poll.vote_raw as text-field
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: feature
