Repository OpenSlides/openslides-backend, pull requests merged in 2022-01, with the labels that each got.

#1109 Add send organization invitation mails
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0009_add_organization_mail_defaults.py
  migrations/tests/test_0009_add_organization_mail_defaults.py
  openslides_backend/action/actions/user/send_invitation_email.py
  openslides_backend/models/models.py
  tests/system/action/user/test_send_invitation_email.py
Labels: high, feature

#1110 Add get_active_users_amount presenter and add some tests.
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/get_active_users_amount.py
  tests/system/presenter/test_get_active_users_amount.py
Labels: high, feature

#1125 Issue1123 new user permission can_manage_presence
  global/meta/models.yml
  global/meta/permission.yml
  openslides_backend/action/actions/user/set_present.py
  openslides_backend/models/models.py
  openslides_backend/permissions/permissions.py
  tests/system/action/user/test_set_present.py
Labels: feature

#1122 Added LABELs to production Dockerfile.
  Dockerfile
Labels: documentation

#1111 Add calculated fields handling to meeting import and meeting clone.
  openslides_backend/action/action.py
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/relations/relation_manager.py
  tests/system/action/meeting/test_import.py
Labels: bug, high

#1112 Allow to set some meeting values in meeting.clone.
  openslides_backend/action/actions/meeting/clone.py
  tests/system/action/meeting/test_clone.py
Labels: feature

#1136 Explicitly pull remote docker repos from main
  .github/docker-compose/docker-compose.prod.yml
  .github/workflows/continuous_integration.yml
  .github/workflows/create-issue-for-file-updates.yml
  LICENSE
  README.md
  dev/docker-compose.dev.yml
  migrations/fetch-example-data.sh
  requirements/partial/requirements_datastore_as_package.txt
  requirements/partial/requirements_production.txt
Labels: bug, blocker, clean up

#1140 Issue1139 Temporarely blocking committee.delete-action
  openslides_backend/action/actions/committee/delete.py
Labels: critical

#1107 Adjust models.yml
  Makefile
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: high

#1146 Add a patch for a problem with mediafile/attachment_ids and clone.
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/models/checker.py
  tests/system/action/meeting/test_clone.py
Labels: bug, critical

#1148 Issue1144 delete projection with historical projector in meeting.delete
  openslides_backend/action/action.py
  openslides_backend/action/actions/assignment_candidate/delete.py
  openslides_backend/action/actions/projection/delete.py
  openslides_backend/action/actions/projector/delete.py
  openslides_backend/action/actions/projector_countdown/delete.py
  tests/system/action/meeting/test_delete.py
  tests/system/action/projection/test_delete.py
Labels: high

#1155 Add get_user_scope presenter and test.
  openslides_backend/action/actions/user/user_scope_permission_check_mixin.py
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/get_user_scope.py
  openslides_backend/shared/mixins/__init__.py
  openslides_backend/shared/mixins/user_scope_mixin.py
  tests/system/presenter/test_get_user_scope.py
Labels: feature

#1154 Add topic to content_object_id of poll and add poll_ids to topic.
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/action/poll/test_create.py
Labels: feature

#1151 Issue1150 Errors on meeting.clone
  openslides_backend/action/actions/agenda_item/agenda_creation.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/models/checker.py
  openslides_backend/models/fields.py
  openslides_backend/services/datastore/commands.py
  tests/system/action/meeting/test_clone.py
Labels: bug, high

#1149 Add sequential_number to some models. Add tests and migrations.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0010_add_sequential_numbers.py
  migrations/tests/conftest.py
  migrations/tests/test_0010_add_sequential_numbers.py
  openslides_backend/action/actions/assignment/create_update_delete.py
  openslides_backend/action/actions/list_of_speakers/create.py
  openslides_backend/action/actions/motion/create_base.py
  openslides_backend/action/actions/motion_block/create_update_delete.py
  openslides_backend/action/actions/motion_category/create_update_delete.py
  openslides_backend/action/actions/motion_comment_section/create.py
  openslides_backend/action/actions/motion_statute_paragraph/create_update_delete.py
  openslides_backend/action/actions/motion_workflow/create.py
  openslides_backend/action/actions/poll/create.py
  openslides_backend/action/actions/projector/create.py
  openslides_backend/action/actions/topic/create.py
  openslides_backend/action/mixins/sequential_numbers_mixin.py
  openslides_backend/models/models.py
  tests/system/action/assignment/test_create.py
  tests/system/action/meeting/test_import.py
  tests/system/action/motion_block/test_create.py
  tests/system/action/motion_category/test_create.py
  tests/system/action/motion_comment_section/test_create.py
  tests/system/action/motion_statute_paragraph/test_create.py
  tests/system/action/motion_workflow/test_create.py
  tests/system/action/poll/test_create.py
  tests/system/action/projector/test_create.py
  tests/system/action/topic/test_create.py
Labels: high, feature

#1166 Add user/pronoun in model,create, update and update_self. Update tests.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/update_self.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_import.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
  tests/system/action/user/test_update_self.py
Labels: feature

#1167 Rename used_as_list_of_speaker_countdown_meeting_id.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0011_rename_used_as_list_of_speaker_countdown_meeting_id.py
  migrations/tests/test_0011_rename_used_as_list_of_speaker_countdown_meeting_id.py
  openslides_backend/action/actions/projector_countdown/delete.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_create.py
  tests/system/action/projector_countdown/test_delete.py
Labels: bug, high

#1174 Active archived meetings in clone meeting. Add some tests.
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_clone.py
Labels: feature

#1170 Set poll/content_object_id to required
  Makefile
  dev/Dockerfile.dev
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/action/poll/test_create.py
Labels: blocker

#1072 Issue1071 Prevent changes for deleted committees on user CML-rights
  Makefile
  cli/generate_models.py
  cli/modelsvalidator/validate.py
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0012_committee_user_relation.py
  migrations/tests/test_0012_committee_user_relation.py
  openslides_backend/action/action.py
  openslides_backend/action/actions/committee/committee_common_mixin.py
  openslides_backend/action/actions/committee/create.py
  openslides_backend/action/actions/committee/update.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/replace_projector_id.py
  openslides_backend/action/actions/meeting/shared_meeting.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/projector/create.py
  openslides_backend/action/actions/projector/update.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/mixins/archived_meeting_check_mixin.py
  openslides_backend/action/relations/calculated_field_handlers_map.py
  openslides_backend/action/relations/relation_manager.py
  openslides_backend/action/relations/user_committee_calculate_handler.py
  openslides_backend/models/base.py
  openslides_backend/models/fields.py
  openslides_backend/models/models.py
  openslides_backend/permissions/permission_helper.py
  openslides_backend/presenter/get_user_related_models.py
  openslides_backend/shared/mixins/user_scope_mixin.py
  openslides_backend/shared/schema.py
  openslides_backend/shared/util_dict_sets.py
  setup.cfg
  tests/system/action/base.py
  tests/system/action/committee/test_create.py
  tests/system/action/committee/test_delete.py
  tests/system/action/committee/test_update.py
  tests/system/action/group/test_delete.py
  tests/system/action/meeting/test_archive.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_delete.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_update.py
  tests/system/action/user/scope_permissions_mixin.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_delete.py
  tests/system/action/user/test_set_present.py
  tests/system/action/user/test_toggle_presence_by_number.py
  tests/system/action/user/test_update.py
  tests/system/base.py
  tests/system/presenter/test_get_user_related_models.py
  tests/system/presenter/test_get_user_scope.py
  tests/system/presenter/test_search_users_by_name_or_email.py
  tests/unit/test_user_scopes.py
Labels: bug, high

#1183 Fix typo in permissions of check_mediafile_id presenter.
  openslides_backend/presenter/check_mediafile_id.py
Labels: bug

#1184 Issue1181 Fix Migration 0012_committee_user_relation
  migrations/migrations/0012_committee_user_relation.py
  migrations/tests/test_0012_committee_user_relation.py
  openslides_backend/action/actions/committee/delete.py
Labels: critical
