Repository OpenSlides/openslides-backend, pull requests merged in 2022-04, with the labels that each got.

#1272 Remove content from error msg, it should not be shown to user.
  openslides_backend/services/datastore/adapter.py
  openslides_backend/services/datastore/extended_adapter.py
  openslides_backend/services/datastore/handle_datastore_errors.py
Labels: bug

#1286 Fix to the raise_datastore_error code. Use new Env.
  openslides_backend/services/datastore/adapter.py
  openslides_backend/services/datastore/extended_adapter.py
  openslides_backend/services/datastore/handle_datastore_errors.py
  openslides_backend/wsgi.py
  tests/unit/extended_datastore_adapter/base.py
  tests/unit/extended_datastore_adapter/test_filter_changed_models.py
Labels: blocker

#1264 #1258 sequential_numbers and mediafile.is_public required, add seq-n…
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/action/action.py
  openslides_backend/action/actions/mediafile/create_directory.py
  openslides_backend/action/actions/mediafile/upload.py
  openslides_backend/action/actions/motion_workflow/import_.py
  openslides_backend/action/actions/organization/initial_import.py
  openslides_backend/models/models.py
  tests/system/action/committee/test_delete.py
  tests/system/action/mediafile/test_create_directory.py
  tests/system/action/mediafile/test_upload.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/motion_workflow/test_import.py
  tests/system/action/organization/test_initial_import.py
  tests/system/action/user/test_delete.py
Labels: bug, critical

#1288 Fix the changed_model filtering for empty mapped_fields
  openslides_backend/services/datastore/extended_adapter.py
  tests/unit/extended_datastore_adapter/test_get.py
Labels: bug, high

#1280 Motion_change_recommendation.create: Fix the collide check.
  global/data/initial-data.json
  migrations/migrations/0024_decrease_motion_change_recommendation_line_to.py
  migrations/tests/test_0024_decrease_motion_change_recommendation_line_to.py
  openslides_backend/action/actions/motion_change_recommendation/create_update_delete.py
  tests/system/action/motion_change_recommendation/test_create.py
Labels: bug

#1289 Improved reader cache
  openslides_backend/action/action.py
  openslides_backend/action/action_handler.py
  openslides_backend/action/actions/option/update.py
  openslides_backend/action/actions/poll/mixins.py
  openslides_backend/action/actions/poll/stop.py
  openslides_backend/action/actions/vote/create.py
  openslides_backend/services/datastore/adapter.py
  openslides_backend/services/datastore/cache_adapter.py
  openslides_backend/services/datastore/commands.py
  openslides_backend/services/datastore/extended_adapter.py
  openslides_backend/services/datastore/interface.py
  requirements/partial/requirements_development.txt
  tests/system/action/poll/test_stop.py
  tests/system/util.py
  tests/unit/extended_datastore_adapter/base.py
Labels: high, performance

#1299 Allow to set 'name' as updated value in meeting.clone
  openslides_backend/action/actions/meeting/clone.py
  tests/system/action/meeting/test_clone.py
Labels: high

#1303 Make group.set_permission more robust.
  openslides_backend/action/actions/group/set_permission.py
  tests/system/action/group/test_set_permission.py
Labels: bug, critical

#1301 Add motion.start_line_number.
  global/meta/models.yml
  openslides_backend/action/actions/motion/update.py
  openslides_backend/models/models.py
  tests/system/action/motion/test_update.py
Labels: high, feature

#1278 Update vote action poll.start, poll.stop and vote/adapter
  openslides_backend/action/action.py
  openslides_backend/action/action_handler.py
  openslides_backend/action/actions/poll/start.py
  openslides_backend/action/actions/poll/stop.py
  openslides_backend/services/vote/adapter.py
Labels: bug

#1296 Add the new forwarding including committee user.
  global/meta/models.yml
  global/meta/permission.yml
  openslides_backend/action/actions/motion/create_forwarded.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/models/models.py
  openslides_backend/permissions/permissions.py
  openslides_backend/presenter/get_forwarding_meetings.py
  tests/system/action/motion/test_create_forwarded.py
  tests/system/action/user/test_create.py
  tests/system/presenter/test_get_forwarding_meetings.py
Labels: high, feature

#1308 Update start_line_number default.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0026_add_start_line_number.py
  migrations/tests/test_0026_add_start_line_number.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_import.py
Labels: high, feature

#1313 Issue1306 meeting.clone
  openslides_backend/action/actions/meeting/clone.py
  tests/system/action/meeting/test_clone.py
Labels: high, feature

#1293 #1074 in-memory migrations for meeting import
  migrations/migrate.py
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/user_mixin.py
  openslides_backend/models/checker.py
  requirements/export_datastore_commit.sh
  tests/system/action/meeting/test_import.py
Labels: high, dependencies

#1315 Issue1314 Change restriction modes for user/forwarding_committee_ids …
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: feature

#1317 Issue931 motion-forwarding in meeting.clone/import, temprorarely dele…
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/models/checker.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
Labels: bug
