Repository OpenSlides/openslides-backend, pull requests merged in 2022-11, with the labels that each got.

#1521 Repair vote service
  dev/docker-compose.dev.yml
  tests/system/action/poll/poll_test_mixin.py
  tests/system/action/poll/test_publish.py
  tests/system/action/poll/test_reset.py
  tests/system/action/poll/test_start.py
  tests/system/action/poll/test_stop.py
  tests/system/action/poll/test_vote.py
Labels: high

#1517 Add optional presence to user.update action and add a test.
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/user/update.py
  tests/system/action/user/test_update.py
Labels: high, feature

#1519 Update motion.set_state, allow a submitter to withdraw.
  global/meta/models.yml
  openslides_backend/action/actions/motion/mixins.py
  openslides_backend/action/actions/motion/set_state.py
  openslides_backend/action/actions/motion_state/update.py
  openslides_backend/models/models.py
  tests/system/action/motion/test_set_state.py
  tests/system/action/motion_state/test_update.py
Labels: feature

#1520 Use local vote-service in make run-dev-local-ds
  Makefile
  dev/dc.local.yml
Labels: feature

#1530 Send a dispatch message to autoupdate on changes
  .github/workflows/create-issue-for-file-updates.yml
Labels: feature

#1534 permission levelling
  global/meta/models.yml
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/user/delete.py
  openslides_backend/action/actions/user/generate_new_password.py
  openslides_backend/action/actions/user/reset_password_to_default.py
  openslides_backend/action/actions/user/set_password.py
  openslides_backend/action/actions/user/user_scope_permission_check_mixin.py
  openslides_backend/models/models.py
  openslides_backend/presenter/get_user_scope.py
  openslides_backend/shared/mixins/user_scope_mixin.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_delete.py
  tests/system/action/user/test_generate_new_password.py
  tests/system/action/user/test_reset_password_to_default.py
  tests/system/action/user/test_set_password.py
  tests/system/action/user/test_update.py
  tests/system/presenter/test_get_user_scope.py
Labels: high

#1537 Issue1536 Exception if there is no instance and no user_id given for get_user_scope
  openslides_backend/shared/mixins/user_scope_mixin.py
  tests/system/presenter/test_get_user_scope.py
Labels: bug

#1540 Remove python minor version from GH actions workflow
  .github/workflows/continuous_integration.yml
Labels: bug, high

#1546 Add motions_block_slide_columns to meeting and allow to update it.
  global/meta/models.yml
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_update.py
Labels: feature
