Repository OpenSlides/openslides-backend, pull requests merged in 2022-03, with the labels that each got.

#1241 Fix & unify internal auth password handling
  openslides_backend/http/views/action_view.py
  openslides_backend/shared/env.py
  tests/system/action/test_general.py
  tests/system/action/test_internal_actions.py
  tests/system/action/util.py
Labels: bug, high

#1243 Fix non-required DecimalField error
  openslides_backend/models/fields.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
Labels: bug, critical

#1238 Use is_partial in checker and update tests.
  cli/check_json.py
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/models/checker.py
  openslides_backend/models/fields.py
  tests/system/action/group/test_create.py
  tests/system/action/meeting/test_delete.py
  tests/system/action/meeting/test_import.py
  tests/system/action/organization/test_initial_import.py
  tests/system/action/user/test_create.py
Labels: clean up, feature

#1252 Strip user names and add tests.
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/user_mixin.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
  tests/system/action/user/test_update_self.py
Labels: bug, high

#1255 Prevent all space in generated usernames.
  openslides_backend/action/actions/user/create.py
  tests/system/action/user/test_create.py
Labels: bug, high

#1231 Issue1215 Adjust is_public calculation for mediafiles, calculate always
  dev/dc.local-ds.yml
  global/data/initial-data.json
  migrations/migrations/0019_calc_mediafile_is_public.py
  migrations/tests/test_0019_calc_mediafile_is_public.py
  openslides_backend/action/actions/group/delete.py
  openslides_backend/action/actions/mediafile/update.py
  openslides_backend/action/actions/mediafile/upload.py
  openslides_backend/models/helper.py
  tests/system/action/group/test_delete.py
  tests/system/action/mediafile/test_update.py
  tests/system/action/mediafile/test_upload.py
Labels: bug, high

#1200 Orga mediafiles
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0021_remove_resource.py
  migrations/migrations/0022_update_mediafile_meeting_id.py
  migrations/tests/test_0021_remove_resource.py
  migrations/tests/test_0022_update_mediafile_meeting_id.py
  openslides_backend/action/action.py
  openslides_backend/action/actions/__init__.py
  openslides_backend/action/actions/mediafile/create_directory.py
  openslides_backend/action/actions/mediafile/delete.py
  openslides_backend/action/actions/mediafile/mixins.py
  openslides_backend/action/actions/mediafile/move.py
  openslides_backend/action/actions/mediafile/update.py
  openslides_backend/action/actions/mediafile/upload.py
  openslides_backend/action/actions/meeting/base_set_mediafile_action.py
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/action/actions/resource/__init__.py
  openslides_backend/action/actions/resource/delete.py
  openslides_backend/action/actions/resource/mixins.py
  openslides_backend/action/actions/resource/upload.py
  openslides_backend/action/util/assert_belongs_to_meeting.py
  openslides_backend/models/checker.py
  openslides_backend/models/models.py
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/check_mediafile_id.py
  openslides_backend/presenter/check_resource_id.py
  tests/system/action/mediafile/test_create_directory.py
  tests/system/action/mediafile/test_delete.py
  tests/system/action/mediafile/test_move.py
  tests/system/action/mediafile/test_update.py
  tests/system/action/mediafile/test_upload.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_set_font.py
  tests/system/action/meeting/test_set_logo.py
  tests/system/action/meeting/test_unset_font.py
  tests/system/action/meeting/test_unset_logo.py
  tests/system/action/motion/test_create.py
  tests/system/action/projector/__init__.py
  tests/system/action/resource/__init__.py
  tests/system/action/resource/test_delete.py
  tests/system/action/resource/test_upload.py
  tests/system/presenter/test_check_mediafile_id.py
  tests/system/presenter/test_check_resource_id.py
Labels: feature

#1257 Add meeting_id filter to some filters
  openslides_backend/action/actions/assignment_candidate/sort.py
  openslides_backend/action/actions/list_of_speakers/re_add_last.py
  openslides_backend/action/actions/motion/update.py
  openslides_backend/action/actions/motion_category/sort_motions_in_category.py
  openslides_backend/action/actions/motion_state/sort.py
  openslides_backend/action/actions/motion_submitter/sort.py
  openslides_backend/action/actions/personal_note/create.py
  openslides_backend/action/actions/projector/toggle.py
  openslides_backend/action/actions/speaker/create.py
  openslides_backend/action/actions/speaker/sort.py
  tests/system/action/list_of_speakers/test_re_add_last.py
  tests/system/action/personal_note/test_create.py
  tests/system/action/speaker/test_create.py
Labels: performance

#1266 Update models.yml for multiple votes per option
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: high, feature

#1265 Remove meeting/enable_chat. Cleanup.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  migrations/migrations/0023_remove_meeting_enable_chat.py
  migrations/tests/test_0023_remove_meeting_enable_chat.py
  openslides_backend/action/actions/chat_group/mixins.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/models/models.py
  tests/system/action/chat_group/test_clear.py
  tests/system/action/chat_group/test_create.py
  tests/system/action/chat_group/test_delete.py
  tests/system/action/chat_group/test_sort.py
  tests/system/action/chat_group/test_update.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_update.py
Labels: clean up

#1263 Refactor calc inherited_access_groups and is_public.
  openslides_backend/action/actions/group/delete.py
  openslides_backend/action/actions/mediafile/calculate_mixins.py
  openslides_backend/action/actions/mediafile/create_directory.py
  openslides_backend/action/actions/mediafile/move.py
  openslides_backend/action/actions/mediafile/update.py
  openslides_backend/action/actions/mediafile/upload.py
  openslides_backend/models/helper.py
  tests/system/action/mediafile/test_create_directory.py
  tests/unit/test_calculate_inherited_groups_helper.py
Labels: clean up

#1251 Multiple votes accumulated on one person
  openslides_backend/action/actions/poll/create.py
  openslides_backend/action/actions/poll/mixins.py
  openslides_backend/action/actions/poll/update.py
  tests/system/action/option/test_update.py
  tests/system/action/poll/test_create.py
  tests/system/action/poll/test_reset.py
  tests/system/action/poll/test_update.py
  tests/system/action/poll/test_vote.py
Labels: feature

#1269 Add a merging of update events after the relation handling
  openslides_backend/action/action.py
  tests/system/action/test_action_command_format.py
Labels: performance

#1249 Some migration route fixes
  README.md
  docs/migration_route.md
  migrations/README.md
  migrations/__init__.py
  migrations/migrate.py
  openslides_backend/migration_handler/migration_handler.py
  openslides_backend/shared/exceptions.py
  openslides_backend/shared/interfaces/logging.py
  requirements/export_datastore_commit.sh
  tests/system/action/test_migration_route.py
Labels: high, clean up, feature

#1275 Fix relation handling bug in generic delete action
  openslides_backend/action/actions/motion/create.py
  openslides_backend/action/generics/delete.py
  tests/system/action/base.py
  tests/system/action/user/test_delete.py
Labels: bug, high

#1277 Rename default state and update tests.
  openslides_backend/action/actions/motion_workflow/create.py
  tests/system/action/meeting/test_create.py
  tests/system/action/motion_workflow/test_create.py
Labels: low
