Repository OpenSlides/openslides-backend, pull requests merged in 2022-05, with the labels that each got.

#1305 Add check for MI in JSON files
  global/data/initial-data.json
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/organization/initial_import.py
  openslides_backend/models/checker.py
  openslides_backend/presenter/export_meeting.py
  setup.cfg
  tests/system/action/meeting/test_import.py
  tests/system/action/organization/test_initial_import.py
Labels: feature

#1322 Change default values for updates to -2
  openslides_backend/action/actions/option/update.py
  openslides_backend/action/actions/poll/update.py
  tests/system/action/option/test_update.py
  tests/system/action/poll/test_update.py
Labels: feature

#1325 #1324 fix poll option error
  openslides_backend/action/actions/option/update.py
  tests/system/action/option/test_update.py
Labels: bug

#1321 Update export_meeting
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/presenter/export_meeting.py
  tests/system/presenter/test_export_meeting.py
Labels: feature

#1318 Issue1052 bulk performance poll
  cli/check_json.py
  cli/modelsvalidator/validate.py
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/poll/delete.py
  openslides_backend/action/actions/poll/reset.py
  openslides_backend/action/actions/poll/stop.py
  openslides_backend/action/actions/user/user_mixin.py
  openslides_backend/action/actions/vote/create.py
  openslides_backend/http/http_exceptions.py
  openslides_backend/models/checker.py
  openslides_backend/permissions/permission_helper.py
  openslides_backend/presenter/export_meeting.py
  openslides_backend/services/datastore/cache_adapter.py
  openslides_backend/services/vote/adapter.py
  openslides_backend/shared/patterns.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_delete.py
  tests/system/action/meeting/test_import.py
  tests/system/action/poll/poll_test_mixin.py
  tests/system/action/poll/test_delete.py
  tests/system/action/poll/test_reset.py
  tests/system/action/poll/test_stop.py
  tests/system/action/poll/test_vote.py
  tests/system/base.py
  tests/system/util.py
  tests/util.py
Labels: bug, high, performance

#1344 Make attachment_ids in motion.create dependent on Mediafile.CAN_SEE
  openslides_backend/action/actions/motion/create.py
  tests/system/action/motion/test_create.py
Labels: bug, critical

#1342 Issue1341 minimize locked_fields for motion.set_state action
  openslides_backend/action/action.py
  openslides_backend/action/actions/motion/set_number_mixin.py
  openslides_backend/action/actions/motion/set_state.py
  openslides_backend/action/util/assert_belongs_to_meeting.py
  tests/system/action/motion/test_set_state.py
  tests/system/action/test_action_command_format.py
Labels: performance

#1345 fix changed_models filter creation for datastore issue 197
  openslides_backend/services/datastore/extended_adapter.py
  tests/unit/extended_datastore_adapter/test_min.py
Labels: bug, blocker
