Repository OpenSlides/openslides-backend, pull requests merged in 2022-10, with the labels that each got.

#1496 Add user/last_login field.
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: feature

#1497 Allow to delete a user, if they are a candidate.
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/action/user/test_delete.py
Labels: bug, high

#1500 Add lock_result to some get/getmany calls
  openslides_backend/action/actions/agenda_item/agenda_creation.py
  openslides_backend/action/actions/agenda_item/numbering.py
  openslides_backend/action/actions/assignment_candidate/delete.py
  openslides_backend/action/actions/assignment_candidate/mixins.py
  openslides_backend/action/actions/chat_group/mixins.py
  openslides_backend/action/actions/chat_group/update.py
  openslides_backend/action/actions/chat_message/create.py
  openslides_backend/action/actions/chat_message/delete.py
  openslides_backend/action/actions/chat_message/update.py
  openslides_backend/action/actions/committee/update.py
  openslides_backend/action/actions/list_of_speakers/create.py
  openslides_backend/action/actions/mediafile/mixins.py
  openslides_backend/action/actions/meeting/archive.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/motion/create_forwarded.py
  openslides_backend/action/actions/motion/delete.py
  openslides_backend/action/actions/motion/follow_recommendation.py
  openslides_backend/action/actions/motion/mixins.py
  openslides_backend/action/actions/motion/motion_state_history_information_mixin.py
  openslides_backend/action/actions/motion/reset_state.py
  openslides_backend/action/actions/motion/set_number_mixin.py
  openslides_backend/action/actions/motion/update.py
  openslides_backend/action/actions/motion_comment/create_delete_update.py
  openslides_backend/action/actions/motion_comment_section/delete.py
  openslides_backend/action/actions/personal_note/delete.py
  openslides_backend/action/actions/personal_note/mixins.py
  openslides_backend/action/actions/personal_note/update.py
  openslides_backend/action/actions/poll/mixins.py
  openslides_backend/action/actions/poll/publish.py
  openslides_backend/action/actions/projection/delete.py
  openslides_backend/action/actions/projector/control_view.py
  openslides_backend/action/actions/projector_countdown/create.py
  openslides_backend/action/actions/projector_countdown/delete.py
  openslides_backend/action/actions/speaker/delete.py
  openslides_backend/action/actions/speaker/mixins.py
  openslides_backend/action/actions/speaker/speak.py
  openslides_backend/action/actions/speaker/update.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/user/forget_password.py
  openslides_backend/action/actions/user/reset_password_to_default.py
  openslides_backend/action/actions/user/set_password_self.py
  openslides_backend/action/actions/user/set_present.py
  openslides_backend/action/actions/user/toggle_presence_by_number.py
  openslides_backend/action/actions/user/user_mixin.py
  openslides_backend/action/actions/user/user_scope_permission_check_mixin.py
Labels: feature

#1483 Add meeting/users_enable_vote_delegations
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/presenter/test_check_database.py
  tests/system/presenter/test_check_database_all.py
Labels: feature

#1455 Assert that assignment poll history works
  openslides_backend/services/datastore/adapter.py
  tests/system/action/base.py
  tests/system/action/motion/test_create_forwarded.py
  tests/system/action/poll/test_update.py
Labels: feature

#1508 Add test and fix a problem with delete assignment candidate with empty user_id
  openslides_backend/action/actions/assignment_candidate/mixins.py
  tests/system/action/assignment_candidate/test_delete.py
Labels: bug

#1510 Add submitter_can_write and logic in motion_comment permissions system.
  global/meta/models.yml
  openslides_backend/action/actions/motion_comment/create_delete_update.py
  openslides_backend/action/actions/motion_comment_section/create.py
  openslides_backend/action/actions/motion_comment_section/update.py
  openslides_backend/models/models.py
  tests/system/action/motion_comment/test_create.py
  tests/system/action/motion_comment/test_delete.py
  tests/system/action/motion_comment/test_update.py
  tests/system/action/motion_comment_section/test_create.py
  tests/system/action/motion_comment_section/test_update.py
Labels: high, feature

#1506 Prefetch fields
  openslides_backend/action/actions/agenda_item/assign.py
  openslides_backend/action/actions/assignment_candidate/create.py
  openslides_backend/action/actions/motion/create.py
  openslides_backend/action/actions/motion/create_forwarded.py
  openslides_backend/action/actions/motion/update.py
  tests/system/action/agenda_item/test_assign.py
  tests/system/action/assignment_candidate/test_create.py
  tests/system/action/motion/test_update.py
Labels: performance

#1515 Use aiosmtpd as python10 hack from r-peschke's fork
  requirements/partial/requirements_development.txt
Labels: high
