Repository OpenSlides/openslides-backend, pull requests merged in 2023-10, with the labels that each got.

#1903 Make `THREAD_WATCH_TIMEOUT` configurable via env var
  README.md
  openslides_backend/action/action_worker.py
  openslides_backend/shared/env.py
  tests/system/base.py
Labels: feature

#1921 Introduce speaker deletion logic to user.update and user.delete
  global/meta/models.yml
  openslides_backend/action/actions/user/conditional_speaker_cascade_mixin.py
  openslides_backend/action/actions/user/delete.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/models/models.py
  tests/system/action/user/test_delete.py
  tests/system/action/user/test_update.py
Labels: bug

#1932 Allow html strikethrough short tag
  openslides_backend/shared/util.py
Labels: feature

#1915 Fix opentelemetry in backend
  openslides_backend/__init__.py
  openslides_backend/main.py
  openslides_backend/shared/otel.py
  requirements/export_datastore_commit.sh
Labels: bug

#1935 Fix speaker.delete and speaker.update for deleted users
  openslides_backend/action/actions/speaker/delete.py
  openslides_backend/action/actions/speaker/update.py
  tests/system/action/speaker/test_delete.py
  tests/system/action/speaker/test_update.py
Labels: bug, high
