Repository OpenSlides/openslides-backend, pull requests merged in 2023-07, with the labels that each got.

#1790 saml_attr_mapping missed null in json schema definition
  openslides_backend/action/actions/organization/update.py
  tests/system/action/organization/test_update.py
Labels: bug

#1794 Bypass the unique check for empty external ids
  openslides_backend/action/actions/committee/committee_common_mixin.py
  openslides_backend/action/actions/group/group_mixin.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/update.py
  tests/system/action/committee/test_create.py
  tests/system/action/group/test_create.py
  tests/system/action/meeting/test_create.py
  tests/system/action/motion/test_update.py
Labels: bug

#1773 Fix clone error
  openslides_backend/action/actions/group/delete.py
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/models/checker.py
  openslides_backend/models/fields.py
  openslides_backend/presenter/check_database.py
  tests/system/action/meeting/test_clone.py
Labels: bug, high

#1791 [feature/remove-template-fields] Fix base permission test
  tests/system/action/base.py
  tests/system/action/motion/test_update.py
Labels: bug

#1805 Change permission of point of order cateory actions
  openslides_backend/action/actions/point_of_order_category/create.py
  openslides_backend/action/actions/point_of_order_category/delete.py
  openslides_backend/action/actions/point_of_order_category/update.py
  tests/system/action/point_of_order_category/test_create.py
  tests/system/action/point_of_order_category/test_delete.py
  tests/system/action/point_of_order_category/test_update.py
Labels: enhancement

#1799 Fix weight assignment in agenda_item.create
  global/meta/models.yml
  openslides_backend/action/actions/agenda_item/agenda_creation.py
  openslides_backend/action/actions/agenda_item/create.py
  openslides_backend/models/models.py
  tests/system/action/agenda_item/test_create.py
  tests/system/action/motion_block/test_create.py
  tests/system/action/topic/test_create.py
Labels: bug

#1793 Fix user deletion with archived meetings
  openslides_backend/presenter/get_user_related_models.py
  openslides_backend/shared/mixins/user_scope_mixin.py
  tests/system/presenter/test_get_user_related_models.py
  tests/system/presenter/test_get_user_scope.py
Labels: bug, high

#1754 [feature/remove-template-fields] Cleanup
  cli/generate_models.py
  openslides_backend/action/actions/chat_message/create.py
  openslides_backend/action/actions/meeting/base_set_mediafile_action.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/meeting/set_font.py
  openslides_backend/action/actions/meeting/set_logo.py
  openslides_backend/action/actions/meeting_user/create.py
  openslides_backend/action/actions/meeting_user/helper.py
  openslides_backend/action/actions/meeting_user/helper_mixin.py
  openslides_backend/action/actions/meeting_user/history_mixin.py
  openslides_backend/action/actions/meeting_user/mixin.py
  openslides_backend/action/actions/meeting_user/set_data.py
  openslides_backend/action/actions/motion/create_base.py
  openslides_backend/action/actions/motion/create_forwarded.py
  openslides_backend/action/actions/motion/set_support_self.py
  openslides_backend/action/actions/motion_comment/create_delete_update.py
  openslides_backend/action/actions/poll/mixins.py
  openslides_backend/action/actions/user/assign_meetings.py
  openslides_backend/action/actions/user/save_saml_account.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/mixins/meeting_user_helper.py
  openslides_backend/action/relations/meeting_user_ids_handler.py
  openslides_backend/action/util/assert_belongs_to_meeting.py
  openslides_backend/action/util/group_mixins.py
  openslides_backend/models/base.py
  openslides_backend/models/checker.py
  openslides_backend/models/fields.py
  openslides_backend/permissions/permission_helper.py
  openslides_backend/presenter/check_mediafile_id.py
  openslides_backend/presenter/get_user_related_models.py
  tests/system/action/group/test_create.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_update.py
  tests/system/migrations/conftest.py
  tests/system/presenter/test_check_mediafile_id.py
  tests/system/relations/setup.py
Labels: clean up

#1807 Add saml_id to search_users presenter
  openslides_backend/presenter/search_users.py
  tests/system/presenter/test_search_users.py
Labels: enhancement

#1806 Add context_id to search_for_id_by_external_id
  openslides_backend/presenter/search_for_id_by_external_id.py
  tests/system/presenter/test_search_for_id_by_external_id.py
Labels: enhancement

#1819 Add tag_ids to topic.create
  openslides_backend/action/actions/topic/create.py
  tests/system/action/topic/test_create.py
Labels: bug

#1800 Rename database env vars & update dependencies
  .github/docker-compose/docker-compose.prod.yml
  Makefile
  cli/modelsvalidator/requirements.txt
  cli/modelsvalidator/setup.cfg
  cli/validate.py
  dev/dc.local.yml
  dev/docker-compose.dev.yml
  requirements/export_datastore_commit.sh
  requirements/partial/requirements_datastore_locally.txt
  requirements/partial/requirements_development.txt
  requirements/partial/requirements_production.txt
  requirements/requirements_cli.txt
  scripts/export_datastore_variables.sh
  tests/util.py
Labels: high, enhancement

#1825 Update gunicorn & datastore
  requirements/export_datastore_commit.sh
  requirements/partial/requirements_production.txt
Labels: bug, dependencies, blocker

#1828 Revert "Add an unique check for motion_category.prefix. (#1626)"
  openslides_backend/action/actions/motion_category/create_update_delete.py
  tests/system/action/motion_category/test_create.py
  tests/system/action/motion_category/test_update.py
Labels: high, feature

#1830 LOS restrict point of order submission to open lists
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/speaker/create.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_update.py
  tests/system/action/speaker/test_create.py
  tests/system/presenter/test_check_database_all.py
Labels: high, feature

#1833 Add two options to workflow import
  openslides_backend/action/actions/motion_workflow/import_.py
  tests/system/action/motion_workflow/test_import.py
Labels: feature

#1832 Allow to set agenda item tags with agenda_tag_ids
  global/meta/models.yml
  openslides_backend/action/actions/agenda_item/agenda_creation.py
  openslides_backend/action/actions/agenda_item/create.py
  openslides_backend/action/actions/topic/create.py
  openslides_backend/action/actions/topic/update.py
  openslides_backend/models/models.py
  tests/system/action/agenda_item/test_create.py
  tests/system/action/agenda_item/test_update.py
  tests/system/action/tag/test_delete.py
  tests/system/action/topic/test_create.py
  tests/system/action/topic/test_update.py
Labels: enhancement
