Repository OpenSlides/openslides-backend, pull requests merged in 2023-01, with the labels that each got.

#1570 Fix example data
  global/data/example-data.json
Labels: clean up

#1489 Adjust dev setup to match main repo
  .github/docker-compose/docker-compose.migrations.yml
  .github/docker-compose/docker-compose.prod.yml
  .github/workflows/continuous_integration.yml
  .gitignore
  dev/dc.local.yml
  dev/docker-compose.dev.yml
  dev/run-tests.sh
  scripts/export_datastore_variables.sh
Labels: high, clean up, feature

#1568 Set password to default password on import
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_import.py
Labels: bug

#1576 Remove presence from user.update and update tests.
  openslides_backend/action/actions/user/update.py
  tests/system/action/user/test_update.py
Labels: bug

#1566 Change `motion/state_id` restriction mode to A
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: feature

#1581 Add project and milestone automatically to new issues & PRs
  .github/workflows/update-new-issues-and-pull-requests.yml
Labels: feature

#1602 Change mode_restriction of motion.state_extension
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: feature

#1603 Fix a UnboundLocalError in checker.
  openslides_backend/models/checker.py
Labels: bug

#1601 Fix user history KeyError
  openslides_backend/action/actions/user/user_mixin.py
Labels: bug

#1605 Cleanup user projection and fix/rm tests.
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/action/meeting/test_import.py
  tests/system/action/projector/test_add_to_preview.py
  tests/system/action/projector/test_project.py
  tests/system/action/user/test_delete.py
  tests/system/presenter/test_export_meeting.py
Labels: clean up, low

#1609 Fix wording for better translations
  openslides_backend/action/actions/motion_workflow/delete.py
  openslides_backend/action/actions/poll/anonymize.py
  tests/system/action/poll/test_anonymize.py
Labels: enhancement
