Repository OpenSlides/openslides-backend, pull requests merged in 2023-03, with the labels that each got.

#1618 Improve email error wording
  openslides_backend/action/actions/user/send_invitation_email.py
  openslides_backend/action/mixins/send_email_mixin.py
  tests/system/action/user/test_send_invitation_email.py
Labels: enhancement

#1656 Fix generic relation handling
  openslides_backend/action/relations/single_relation_handler.py
  tests/system/relations/setup.py
  tests/system/relations/test_generic_relations.py
  tests/system/relations/test_relations.py
Labels: bug

#1655 Improve action_worker logging, add action_names to log msgs.
  openslides_backend/action/action_worker.py
  tests/system/action/test_action_worker.py
Labels: feature

#1659 Fix payload of file generation trigger
  .github/workflows/create-issue-for-file-updates.yml
Labels: bug

#1666 Fix history entry for multiple forwardings
  openslides_backend/action/actions/motion/create_forwarded.py
  tests/system/action/motion/test_create_forwarded.py
Labels: bug

#1669 Fix user update permissions
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/user/user_mixin.py
  openslides_backend/presenter/get_user_scope.py
  openslides_backend/shared/mixins/user_scope_mixin.py
  tests/system/action/user/test_update.py
  tests/system/presenter/test_get_user_scope.py
Labels: bug, high

#1670 Fix schema usages
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/motion_workflow/import_.py
  openslides_backend/action/actions/projector/add_to_preview.py
  openslides_backend/action/actions/projector/project.py
  openslides_backend/action/actions/projector/sort_preview.py
  openslides_backend/action/actions/user/forget_password_confirm.py
  openslides_backend/action/util/default_schema.py
  openslides_backend/presenter/get_user_related_models.py
  openslides_backend/presenter/get_user_scope.py
  openslides_backend/presenter/get_users.py
  openslides_backend/shared/schema.py
Labels: clean up

#1658 Allow iframe and add sandbox to it. Update tests.
  openslides_backend/shared/util.py
  tests/system/action/meeting/test_settings.py
  tests/system/action/topic/test_update.py
Labels: feature

#1674 implement ListUpdateEvent for instance-recreation in import
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_import.py
Labels: high

#1663 Change `search_users` presenter
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/get_user_scope.py
  openslides_backend/presenter/search_users.py
  openslides_backend/services/datastore/commands.py
  openslides_backend/shared/filters.py
  openslides_backend/shared/mixins/user_scope_mixin.py
  tests/system/presenter/test_search_users.py
  tests/system/util.py
  tests/unit/test_filters.py
Labels: bug, high, waiting

#1679 Add meeting/topic_poll_default_group_ids
  global/meta/models.yml
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_update.py
Labels: feature

#1672 I1660 rm tf reactivate tests
  dev/docker-compose.dev.yml
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/action/actions/meeting_user/create.py
  openslides_backend/action/actions/meeting_user/mixin.py
  openslides_backend/action/actions/meeting_user/update.py
  openslides_backend/action/actions/poll/mixins.py
  openslides_backend/action/actions/poll/stop.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/vote/create.py
  openslides_backend/action/relations/relation_manager.py
  openslides_backend/models/models.py
  tests/system/action/base.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting_user/test_create.py
  tests/system/action/meeting_user/test_create_delegation.py
  tests/system/action/meeting_user/test_update.py
  tests/system/action/meeting_user/test_update_delegation.py
  tests/system/action/poll/poll_test_mixin.py
  tests/system/action/poll/test_anonymize.py
  tests/system/action/poll/test_delete.py
  tests/system/action/poll/test_reset.py
  tests/system/action/poll/test_start.py
  tests/system/action/poll/test_stop.py
  tests/system/action/poll/test_update.py
  tests/system/action/poll/test_vote.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_delete.py
  tests/system/action/user/test_send_invitation_email.py
  tests/system/action/user/test_update.py
  tests/system/migrations/test_0012_committee_user_relation.py
  tests/system/presenter/test_check_database.py
  tests/system/presenter/test_check_database_all.py
  tests/system/presenter/test_export_meeting.py
  tests/system/relations/setup.py
  tests/system/relations/test_structured_relations.py
  tests/system/relations/test_template_fields.py
Labels: enhancement

#1685 Add the new opt colors headbar/yes/no/abstain to theme.
  global/meta/models.yml
  openslides_backend/action/actions/theme/create.py
  openslides_backend/models/models.py
  tests/system/action/theme/test_create.py
  tests/system/action/theme/test_update.py
Labels: feature

#1682 I1681 remove template fields related code
  cli/generate_models.py
  cli/modelsvalidator/validate.py
  openslides_backend/action/action.py
  openslides_backend/action/actions/chat_message/create.py
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/motion/update.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/delete.py
  openslides_backend/action/actions/user/user_mixin.py
  openslides_backend/action/generics/delete.py
  openslides_backend/action/mixins/archived_meeting_check_mixin.py
  openslides_backend/action/relations/relation_manager.py
  openslides_backend/action/relations/single_relation_handler.py
  openslides_backend/models/base.py
  openslides_backend/models/checker.py
  openslides_backend/models/fields.py
  openslides_backend/shared/util_dict_sets.py
  tests/system/action/chat_message/test_create.py
  tests/system/action/meeting/test_delete.py
  tests/system/action/motion/test_update.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
  tests/system/relations/setup.py
Labels: clean up
