Repository OpenSlides/openslides-backend, pull requests merged in 2023-02, with the labels that each got.

#1617 In meeting.set_logo allow image/svg+xml.
  openslides_backend/action/actions/meeting/set_logo.py
  tests/system/action/meeting/test_set_logo.py
Labels: feature

#1575 Ignore action_worker meeting-import/export and datastore checker.
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/presenter/check_database_all.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/presenter/test_check_database_all.py
  tests/system/presenter/test_export_meeting.py
Labels: bug

#1615 Add poll_candidate and poll_candidate_list.
  global/meta/models.yml
  openslides_backend/action/actions/__init__.py
  openslides_backend/action/actions/option/create.py
  openslides_backend/action/actions/option/delete.py
  openslides_backend/action/actions/poll/create.py
  openslides_backend/action/actions/poll_candidate/__init__.py
  openslides_backend/action/actions/poll_candidate/create.py
  openslides_backend/action/actions/poll_candidate/delete.py
  openslides_backend/action/actions/poll_candidate_list/__init__.py
  openslides_backend/action/actions/poll_candidate_list/create.py
  openslides_backend/action/actions/poll_candidate_list/delete.py
  openslides_backend/action/relations/single_relation_handler.py
  openslides_backend/models/models.py
  tests/system/action/option/test_create.py
  tests/system/action/poll/test_create.py
  tests/system/action/poll/test_delete.py
  tests/system/action/poll_candidate/__init__.py
  tests/system/action/poll_candidate/test_create.py
  tests/system/action/poll_candidate/test_delete.py
  tests/system/action/poll_candidate_list/__init__.py
  tests/system/action/poll_candidate_list/test_create.py
  tests/system/action/poll_candidate_list/test_delete.py
Labels: high, feature

#1625 Add EmailCheckMixin and configure it in some actions.
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/organization/update.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/forget_password.py
  openslides_backend/action/actions/user/send_invitation_email.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/update_self.py
  openslides_backend/action/mixins/send_email_mixin.py
  tests/system/action/mail_base.py
  tests/system/action/meeting/test_update.py
  tests/system/action/organization/test_update.py
  tests/system/action/test_send_email_mixin.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
  tests/system/action/user/test_update_self.py
Labels: bug

#1626 Add an unique check for motion_category.prefix.
  openslides_backend/action/actions/motion_category/create_update_delete.py
  tests/system/action/motion_category/test_create.py
  tests/system/action/motion_category/test_update.py
Labels: high, feature

#1629 motion.state_id restriction_mode back to C
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: high

#1627 Update dependencies
  openslides_backend/action/action.py
  openslides_backend/action/action_handler.py
  openslides_backend/action/actions/agenda_item/agenda_tree.py
  openslides_backend/action/actions/mediafile/upload.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/motion/create_base.py
  openslides_backend/action/actions/motion/follow_recommendation.py
  openslides_backend/action/mixins/send_email_mixin.py
  openslides_backend/action/mixins/sequential_numbers_mixin.py
  openslides_backend/action/relations/calculated_field_handler.py
  openslides_backend/action/relations/user_committee_calculate_handler.py
  openslides_backend/migrations/migrate.py
  openslides_backend/migrations/migration_handler.py
  openslides_backend/migrations/migrations/0006_add_required_theme_id.py
  openslides_backend/migrations/migrations/0021_remove_resource.py
  openslides_backend/migrations/migrations/0029_update_organization_user_ids.py
  openslides_backend/models/base.py
  openslides_backend/models/fields.py
  openslides_backend/permissions/management_levels.py
  openslides_backend/presenter/base.py
  openslides_backend/presenter/presenter_interface.py
  openslides_backend/services/datastore/adapter.py
  openslides_backend/services/datastore/cache_adapter.py
  openslides_backend/services/datastore/extended_adapter.py
  openslides_backend/services/datastore/handle_datastore_errors.py
  openslides_backend/services/datastore/interface.py
  openslides_backend/services/media/interface.py
  openslides_backend/services/vote/interface.py
  openslides_backend/shared/interfaces/env.py
  openslides_backend/shared/interfaces/logging.py
  openslides_backend/shared/interfaces/wsgi.py
  openslides_backend/shared/otel.py
  openslides_backend/shared/util.py
  requirements/export_datastore_commit.sh
  requirements/partial/requirements_datastore_locally.txt
  requirements/partial/requirements_development.txt
  requirements/partial/requirements_production.txt
  requirements/requirements_cli.txt
  requirements/requirements_development.txt
  requirements/requirements_migrations.txt
  setup.cfg
  tests/system/action/committee/test_create.py
  tests/system/action/mail_base.py
  tests/system/action/mediafile/test_upload.py
  tests/system/action/motion/test_create_sequential_number.py
  tests/system/action/test_migration_route.py
  tests/system/action/user/test_send_invitation_email.py
  tests/system/base.py
  tests/system/migrations/test_0005_remove_organization_theme.py
  tests/system/migrations/test_0010_add_sequential_numbers.py
  tests/system/migrations/test_0016_remove_url_name_and_users_pdf_url.py
  tests/system/migrations/test_0018_remove_template_meeting_committee_relation.py
  tests/system/migrations/test_0020_2nd_migration_seq_numbers.py
  tests/system/migrations/test_0021_remove_resource.py
  tests/system/migrations/test_0031_remove_permission_user_can_see_extra_data.py
  tests/system/util.py
  tests/unit/test_calculate_inherited_groups_helper.py
Labels: dependencies, clean up

#1633 Add a check unique number to motion.update.
  openslides_backend/action/actions/motion/update.py
  tests/system/action/motion/test_update.py
Labels: high, feature

#1593 Issue1592 fix some restriction modes lost on moving template fields f…
  .github/docker-compose/docker-compose.prod.yml
  .github/workflows/continuous_integration.yml
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/action/meeting/test_import.py
Labels: bug

#1579 Add migration to remove unnecessary events
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/migrations/migrations/0034_remove_unnecessary_events.py
  tests/system/migrations/test_0034_remove_unnecessary_events.py
Labels: feature, migration

#1544 Extension field migration
  cli/modelsvalidator/validate.py
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/action/actions/motion/update.py
  openslides_backend/migrations/migrations/0035_fix_motion_extension_fields.py
  openslides_backend/models/checker.py
  openslides_backend/models/fields.py
  openslides_backend/shared/patterns.py
  openslides_backend/shared/schema.py
  tests/system/action/motion/test_update.py
  tests/system/action/projector/test_project.py
  tests/system/migrations/conftest.py
  tests/system/migrations/test_0035_fix_motion_extension_fields.py
Labels: bug, high, migration

#1619 Rename default_projector_$_id and use a list field for it.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/replace_projector_id.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/migrations/migrations/0036_rename_change_default_projector_ids.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_replace_projector_id.py
  tests/system/action/meeting/test_update.py
  tests/system/action/projector/test_create.py
  tests/system/action/projector/test_delete.py
  tests/system/action/projector/test_update.py
  tests/system/migrations/test_0036_rename_change_default_projector_ids.py
  tests/system/presenter/test_check_database.py
  tests/system/presenter/test_check_database_all.py
Labels: feature, migration

#1610 Add permissions array to `group.update`
  openslides_backend/action/actions/group/__init__.py
  openslides_backend/action/actions/group/set_permission.py
  openslides_backend/action/actions/group/update.py
  tests/system/action/group/test_set_permission.py
  tests/system/action/group/test_update.py
Labels: feature, waiting

#1639 Fix extension migration
  openslides_backend/migrations/migrations/0035_fix_motion_extension_fields.py
  tests/system/migrations/test_0035_fix_motion_extension_fields.py
Labels: bug, high

#1624 Fix `motion.set_state` bulk action
  openslides_backend/action/actions/motion/follow_recommendation.py
  openslides_backend/action/actions/motion/mixins.py
  openslides_backend/action/actions/motion/set_state.py
  tests/system/action/motion/test_set_state.py
Labels: bug, clean up

#1641 Fix user projection migration
  openslides_backend/migrations/migrations/0037_remove_user_projections.py
  tests/system/migrations/test_0037_remove_user_projections.py
Labels: bug, high

#1636 Update test postgres from 11 to 13.
  .github/docker-compose/docker-compose.prod.yml
  dev/docker-compose.dev.yml
Labels: feature

#1640 Add meeting_user.set_data and use it in user actions.
  openslides_backend/action/actions/meeting_user/__init__.py
  openslides_backend/action/actions/meeting_user/set_data.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/user_mixin.py
  tests/system/action/meeting_user/test_set_data.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
Labels: feature

#1635 Add blacklist of letters to users_email_sender.
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/organization/update.py
  openslides_backend/action/mixins/send_email_mixin.py
  tests/system/action/meeting/test_update.py
  tests/system/action/organization/test_update.py
Labels: bug, low

#1645 Update Ubuntu version to 22.04 for prod image test in CI
  .github/workflows/continuous_integration.yml
Labels: bug, tests

#1643 Add migration for rm user default projector.
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/migrations/migrations/0038_remove_user_default_projector.py
  tests/system/migrations/test_0038_remove_user_default_projector.py
Labels: bug, migration

#1652 Add check for the tested fields
  tests/system/action/meeting/test_import.py
  tests/system/base.py
Labels: tests
