Repository OpenSlides/openslides-backend, pull requests merged in 2023-05, with the labels that each got.

#1720 Add optional pip dependency to support pdf crypto
  requirements/partial/requirements_production.txt
Labels: dependencies

#1723 Add ShortCharField and use it for pronoun.
  cli/generate_models.py
  cli/modelsvalidator/validate.py
  global/meta/models.yml
  openslides_backend/models/fields.py
  openslides_backend/models/models.py
  tests/system/action/user/test_update.py
Labels: feature

#1697 Add account import
  openslides_backend/action/action.py
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/topic/import_.py
  openslides_backend/action/actions/topic/json_upload.py
  openslides_backend/action/actions/user/__init__.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/import_.py
  openslides_backend/action/actions/user/json_upload.py
  openslides_backend/action/actions/user/user_mixin.py
  openslides_backend/action/mixins/import_mixins.py
  openslides_backend/presenter/check_database.py
  openslides_backend/presenter/export_meeting.py
  openslides_backend/shared/export_helper.py
  tests/system/action/topic/test_import.py
  tests/system/action/topic/test_json_upload.py
  tests/system/action/user/test_import.py
  tests/system/action/user/test_json_upload.py
Labels: feature

#1653 Rename last_email_send and default_100_percent.
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/poll/base.py
  openslides_backend/action/actions/poll/create.py
  openslides_backend/action/actions/poll/update.py
  openslides_backend/action/actions/user/forget_password.py
  openslides_backend/action/actions/user/send_invitation_email.py
  openslides_backend/migrations/migrations/0040_rename_last_email_send_and_100.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/action/user/test_forget_password.py
  tests/system/action/user/test_send_invitation_email.py
  tests/system/migrations/test_0040_rename_last_email_send_and_100.py
  tests/system/presenter/test_check_database.py
  tests/system/presenter/test_check_database_all.py
Labels: clean up, low, waiting, migration

#1728 Replace short_string type with maxLength attribute
  cli/generate_models.py
  cli/modelsvalidator/validate.py
  global/meta/models.yml
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/models/fields.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_create.py
  tests/system/action/user/test_update.py
Labels: documentation, clean up

#1729 Add HEALTHCHECK to productive Dockerfile
  Dockerfile
Labels: feature

#1735 Implement structure for model migrations
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/migrations/migrate.py
  openslides_backend/migrations/migration_wrapper.py
  openslides_backend/migrations/migrations/0002_archive_meetings.py
  openslides_backend/migrations/migrations/0005_remove_organization_theme.py
  openslides_backend/migrations/migrations/0006_add_required_theme_id.py
  openslides_backend/migrations/migrations/0009_add_organization_mail_defaults.py
  openslides_backend/migrations/migrations/0010_add_sequential_numbers.py
  openslides_backend/migrations/migrations/0011_rename_used_as_list_of_speaker_countdown_meeting_id.py
  openslides_backend/migrations/migrations/0012_committee_user_relation.py
  openslides_backend/migrations/migrations/0013_archived_meeting_ids.py
  openslides_backend/migrations/migrations/0014_rename_template_meeting_id.py
  openslides_backend/migrations/migrations/0019_calc_mediafile_is_public.py
  openslides_backend/migrations/migrations/0020_2nd_migration_seq_numbers.py
  openslides_backend/migrations/migrations/0021_remove_resource.py
  openslides_backend/migrations/migrations/0022_update_mediafile_meeting_id.py
  openslides_backend/migrations/migrations/0024_decrease_motion_change_recommendation_line_to.py
  openslides_backend/migrations/migrations/0028_rename_motion_sort_children_ids.py
  openslides_backend/migrations/migrations/0029_update_organization_user_ids.py
  openslides_backend/migrations/migrations/0031_remove_permission_user_can_see_extra_data.py
  openslides_backend/migrations/migrations/0032_fix_motion_origin_relations.py
  openslides_backend/migrations/migrations/0034_remove_unnecessary_events.py
  openslides_backend/migrations/migrations/0035_fix_motion_extension_fields.py
  openslides_backend/migrations/migrations/0036_rename_change_default_projector_ids.py
  openslides_backend/migrations/migrations/0037_remove_user_projections.py
  openslides_backend/migrations/migrations/0038_remove_user_default_projector.py
  openslides_backend/migrations/migrations/0040_rename_last_email_send_and_100.py
  openslides_backend/models/checker.py
  openslides_backend/presenter/presenter_interface.py
  openslides_backend/services/datastore/commands.py
  openslides_backend/services/datastore/extended_adapter.py
  openslides_backend/shared/interfaces/env.py
  openslides_backend/shared/interfaces/logging.py
  openslides_backend/shared/interfaces/services.py
  openslides_backend/shared/interfaces/wsgi.py
  openslides_backend/shared/schema.py
  requirements/export_datastore_commit.sh
  setup.cfg
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/action/test_migration_route.py
  tests/system/util.py
  tests/unit/extended_datastore_adapter/base.py
  tests/unit/extended_datastore_adapter/test_filter_changed_models.py
Labels: high, feature

#1740 Fix output for migration stats command
  openslides_backend/migrations/migration_wrapper.py
Labels: bug, low

#1741 Fix `check_database` presenter and add `check_database` CLI script
  cli/check_database.py
  openslides_backend/action/actions/meeting/export_helper.py
  openslides_backend/http/application.py
  openslides_backend/presenter/check_database.py
  openslides_backend/presenter/check_database_all.py
  openslides_backend/services/datastore/extended_adapter.py
  openslides_backend/services/datastore/interface.py
Labels: bug
