Repository OpenSlides/openslides-backend, pull requests merged in 2023-04, with the labels that each got.

#1689 I1649 some required changes
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/action/actions/chat_message/create.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting_user/mixin.py
  openslides_backend/action/actions/projector/create.py
  openslides_backend/action/actions/projector/update.py
  openslides_backend/models/models.py
  openslides_backend/presenter/get_user_related_models.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_replace_projector_id.py
  tests/system/action/meeting/test_update.py
  tests/system/action/meeting_user/test_create.py
  tests/system/action/meeting_user/test_update.py
  tests/system/action/motion/test_create.py
  tests/system/action/motion/test_create_forwarded.py
  tests/system/action/motion/test_delete.py
  tests/system/action/motion/test_set_state.py
  tests/system/action/motion/test_update.py
  tests/system/action/motion_comment/test_create.py
  tests/system/action/motion_comment/test_delete.py
  tests/system/action/motion_comment/test_update.py
  tests/system/action/motion_submitter/test_create.py
  tests/system/action/projector/test_create.py
  tests/system/action/projector/test_delete.py
  tests/system/action/projector/test_update.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_delete.py
  tests/system/presenter/test_check_database.py
  tests/system/presenter/test_check_database_all.py
  tests/system/presenter/test_export_meeting.py
  tests/system/presenter/test_get_user_related_models.py
Labels: clean up, enhancement

#1692 Add minimum to projector/scroll.
  global/meta/models.yml
  openslides_backend/action/actions/projector/control_view.py
  openslides_backend/models/models.py
  tests/system/action/projector/test_control_view.py
Labels: feature

#1691 Issue1680 write_action_worker with delete
  requirements/export_datastore_commit.sh
  tests/system/action/test_action_worker.py
Labels: feature

#1690 [feature/remove-template-fields] Reactivate user history
  openslides_backend/action/action.py
  openslides_backend/action/actions/meeting_user/create.py
  openslides_backend/action/actions/meeting_user/delete.py
  openslides_backend/action/actions/meeting_user/mixin.py
  openslides_backend/action/actions/meeting_user/set_data.py
  openslides_backend/action/actions/meeting_user/update.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/delete.py
  openslides_backend/action/actions/user/user_mixin.py
  tests/system/action/base.py
  tests/system/action/meeting_user/test_update.py
  tests/system/action/meeting_user/test_update_delegation.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_delete.py
  tests/system/action/user/test_update.py
Labels: bug

#1678 Add topic.json_upload/import
  openslides_backend/action/actions/topic/__init__.py
  openslides_backend/action/actions/topic/import_.py
  openslides_backend/action/actions/topic/json_upload.py
  openslides_backend/action/actions/topic/mixins.py
  tests/system/action/topic/test_import.py
  tests/system/action/topic/test_json_upload.py
Labels: feature

#1707 Add a check for only one start_time and end time.
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/mixins.py
  openslides_backend/action/actions/meeting/update.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_update.py
Labels: feature

#1703 Ensure stack-internal actions can only be executed stack-internally
  openslides_backend/action/action_handler.py
  openslides_backend/shared/interfaces/wsgi.py
  tests/system/action/test_internal_actions.py
  tests/system/action/test_migration_route.py
  tests/system/util.py
Labels: bug, high
