Repository OpenSlides/openslides-backend, pull requests merged in 2023-12, with the labels that each got.

#2034 Remove copying of `block_id` from amendment creation
  openslides_backend/action/actions/motion/create.py
  tests/system/action/motion/test_create.py
  tests/system/action/motion/test_create_amendment.py
  tests/system/action/motion/test_set_number_mixin.py
Labels: enhancement

#2033 Add global options to poll create
  openslides_backend/action/actions/poll/create.py
  tests/system/action/poll/test_create.py
Labels: bug

#2036 Update authlib
  openslides_backend/action/actions/user/set_password_self.py
  openslides_backend/services/auth/adapter.py
  openslides_backend/services/auth/interface.py
  requirements/partial/requirements_production.txt
  tests/system/action/meeting/test_import.py
  tests/system/action/test_internal_actions.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_forget_password_confirm.py
  tests/system/action/user/test_generate_new_password.py
  tests/system/action/user/test_reset_password_to_default.py
  tests/system/action/user/test_set_password.py
  tests/system/action/user/test_set_password_self.py
Labels: dependencies

#2038 get_forwarding_meetings: Make meeting_id required
  openslides_backend/presenter/get_forwarding_meetings.py
  tests/system/presenter/test_get_forwarding_meetings.py
Labels: bug

#2031 Check for mimetype via content
  .github/workflows/continuous_integration.yml
  Dockerfile
  dev/Dockerfile.dev
  openslides_backend/action/actions/mediafile/upload.py
  requirements/partial/requirements_production.txt
  tests/system/action/mediafile/test_upload.py
  tests/system/util.py
Labels: bug, high

#1980 I1714 Participant Import
  openslides_backend/action/action.py
  openslides_backend/action/actions/topic/import_.py
  openslides_backend/action/actions/user/__init__.py
  openslides_backend/action/actions/user/account_import.py
  openslides_backend/action/actions/user/account_json_upload.py
  openslides_backend/action/actions/user/base_import.py
  openslides_backend/action/actions/user/base_json_upload.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/user/participant_common.py
  openslides_backend/action/actions/user/participant_import.py
  openslides_backend/action/actions/user/participant_json_upload.py
  openslides_backend/action/mixins/import_mixins.py
  openslides_backend/shared/mixins/user_scope_mixin.py
  tests/system/action/base.py
  tests/system/action/topic/test_import.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
  tests/system/action/user/test_update.py
Labels: feature

#2042 Allow `list_of_speakers.re_add_last` for point of order speakers
  openslides_backend/action/actions/list_of_speakers/re_add_last.py
  tests/system/action/list_of_speakers/test_re_add_last.py
Labels: bug

#2046 Make text-type mimetype recognition more lenient
  openslides_backend/action/actions/mediafile/upload.py
  tests/system/action/mediafile/test_upload.py
Labels: bug, high

#2056 Use new structure level in participant import
  openslides_backend/action/actions/user/base_import.py
  openslides_backend/action/actions/user/base_json_upload.py
  openslides_backend/action/actions/user/participant_import.py
  openslides_backend/action/actions/user/participant_json_upload.py
  openslides_backend/action/mixins/import_mixins.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug

#2061 Fix race condition test
  README.md
  openslides_backend/action/action_worker.py
  tests/system/action/motion/test_create_sequential_number.py
Labels: bug, tests

#2050 Add enum to `import_preview/name`
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/action/meeting/test_clone.py
  tests/system/presenter/test_check_database_all.py
  tests/system/presenter/test_export_meeting.py
Labels: clean up

#2057 svg and json as html/plain working
  openslides_backend/action/actions/mediafile/upload.py
  requirements/partial/requirements_development.txt
  requirements/partial/requirements_production.txt
  tests/system/action/mediafile/test_upload.py
Labels: bug, high

#2041 Logout after password change
  .github/workflows/continuous_integration.yml
  Dockerfile
  README.md
  dev/Dockerfile.dev
  dev/dc.local.yml
  dev/docker-compose.dev.yml
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/user/base_json_upload.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/user/forget_password.py
  openslides_backend/action/actions/user/forget_password_confirm.py
  openslides_backend/action/actions/user/generate_new_password.py
  openslides_backend/action/actions/user/helper.py
  openslides_backend/action/actions/user/password_mixin.py
  openslides_backend/action/actions/user/password_mixins.py
  openslides_backend/action/actions/user/reset_password_to_default.py
  openslides_backend/action/actions/user/save_saml_account.py
  openslides_backend/action/actions/user/send_invitation_email.py
  openslides_backend/action/actions/user/set_password.py
  openslides_backend/action/actions/user/set_password_self.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/update_self.py
  openslides_backend/action/actions/user/user_mixins.py
  openslides_backend/http/application.py
  openslides_backend/http/views/action_view.py
  openslides_backend/http/views/base_view.py
  openslides_backend/presenter/presenter.py
  openslides_backend/services/auth/adapter.py
  openslides_backend/services/auth/interface.py
  openslides_backend/services/shared/__init__.py
  openslides_backend/services/shared/authenticated_service.py
  openslides_backend/services/vote/adapter.py
  openslides_backend/services/vote/interface.py
  requirements/export_service_commits.sh
  requirements/partial/requirements_datastore_as_package.txt
  requirements/partial/requirements_local_services.txt
  requirements/partial/requirements_packaged_services.txt
  requirements/partial/requirements_production.txt
  requirements/requirements_development_local.txt
  requirements/requirements_production.txt
  tests/system/action/base.py
  tests/system/action/user/test_forget_password.py
  tests/system/action/user/test_forget_password_confirm.py
  tests/system/action/user/test_generate_new_password.py
  tests/system/action/user/test_reset_password_to_default.py
  tests/system/action/user/test_set_password.py
  tests/system/action/user/test_set_password_self.py
Labels: high, feature, waiting

#2051 Fix participant KeyError and improve account warning messages in imports
  openslides_backend/action/actions/user/base_import.py
  openslides_backend/action/actions/user/base_json_upload.py
  openslides_backend/action/actions/user/participant_import.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug, critical

#2063 Use postgres 15 images + debian bookworm images
  .github/docker-compose/docker-compose.prod.yml
  Dockerfile
  dev/Dockerfile.dev
  dev/docker-compose.dev.yml
  tests/system/action/test_send_email_mixin.py
  tests/system/action/user/test_send_invitation_email.py
Labels: dependencies

#2068 Add `merge_group` CI trigger
  .github/workflows/continuous_integration.yml
Labels: enhancement

#2069 Try to fix failing auth token test
  tests/system/action/base.py
  tests/system/action/motion/test_create_sequential_number.py
Labels: bug, tests

#2072 Fix CI for local setup
  .github/workflows/continuous_integration.yml
Labels: bug
