Repository OpenSlides/openslides-backend, pull requests merged in 2023-11, with the labels that each got.

#1937 I1936_fix_import_lookup_duplicates
  openslides_backend/action/mixins/import_mixins.py
  tests/system/action/topic/test_json_upload.py
  tests/system/action/user/test_account_json_upload.py
Labels: bug

#1938 Prevent vote weight of 0
  cli/validate.py
  global/meta/models.yml
  openslides_backend/main.py
  openslides_backend/models/fields.py
  openslides_backend/models/models.py
  tests/system/action/meeting_user/test_set_data.py
  tests/system/action/user/test_update.py
Labels: feature

#1924 Add `dependabot.yml`
  .github/dependabot.yml
Labels: dependencies, enhancement

#1946 Fix dependency structure for dependabot
  .github/dependabot.yml
  requirements/partial/requirements_datastore_locally.txt
  requirements/requirements_development_local_ds.txt
Labels: enhancement

#1947 Fix presenter error
  openslides_backend/permissions/permission_helper.py
Labels: bug

#1959 Increase dependabot limit and group otel updates
  .github/dependabot.yml
Labels: enhancement

#1975 Update datastore & improve dep tests
  .github/dependabot.yml
  .github/workflows/continuous_integration.yml
  dev/run-local.sh
  requirements/export_datastore_commit.sh
  requirements/partial/requirements_datastore_locally.txt
  requirements/partial/requirements_production.txt
  tests/system/action/assignment/test_create.py
  tests/system/action/committee/test_create.py
  tests/system/action/group/test_create.py
  tests/system/action/mediafile/test_upload.py
  tests/system/action/meeting/test_import.py
  tests/system/action/motion_block/test_create.py
  tests/system/action/motion_category/test_create.py
  tests/system/action/motion_change_recommendation/test_create.py
  tests/system/action/motion_comment_section/test_create.py
  tests/system/action/motion_statute_paragraph/test_create.py
  tests/system/action/motion_submitter/test_create.py
  tests/system/action/motion_workflow/test_create.py
  tests/system/action/organization_tag/test_create.py
  tests/system/action/projector/test_project.py
  tests/system/action/projector_message/test_create.py
  tests/system/action/speaker/test_create_point_of_order.py
  tests/system/action/tag/test_create.py
  tests/system/action/theme/test_create.py
  tests/system/action/user/test_merge_together.py
Labels: enhancement

#1981 Add model & permission changes for the LoS extension
  cli/generate_permissions.py
  global/meta/models.yml
  global/meta/permission.yml
  openslides_backend/models/checker.py
  openslides_backend/models/models.py
  openslides_backend/permissions/permissions.py
Labels: needs discussion, feature, los-extension

#1994 Fix personal note handling & `equal_fields`
  global/meta/models.yml
  openslides_backend/action/actions/meeting_user/mixin.py
  openslides_backend/action/actions/personal_note/create.py
  openslides_backend/models/models.py
  tests/system/action/meeting_user/test_create.py
  tests/system/action/meeting_user/test_update.py
  tests/system/action/personal_note/test_create.py
Labels: clean up, enhancement

#1989 Add basic structure level functionality
  openslides_backend/action/actions/__init__.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/structure_level/__init__.py
  openslides_backend/action/actions/structure_level/create.py
  openslides_backend/action/actions/structure_level/delete.py
  openslides_backend/action/actions/structure_level/update.py
  tests/system/action/structure_level/__init__.py
  tests/system/action/structure_level/test_create.py
  tests/system/action/structure_level/test_delete.py
  tests/system/action/structure_level/test_update.py
Labels: feature, los-extension

#1991 Add basic functionality for the `structure_level_list_of_speakers` collection
  openslides_backend/action/actions/__init__.py
  openslides_backend/action/actions/structure_level_list_of_speakers/__init__.py
  openslides_backend/action/actions/structure_level_list_of_speakers/create.py
  openslides_backend/action/actions/structure_level_list_of_speakers/delete.py
  tests/system/action/structure_level_list_of_speakers/__init__.py
  tests/system/action/structure_level_list_of_speakers/test_create.py
  tests/system/action/structure_level_list_of_speakers/test_delete.py
Labels: feature, los-extension

#1992 Add action `structure_level_list_of_speakers.add_time`
  openslides_backend/action/actions/structure_level_list_of_speakers/__init__.py
  openslides_backend/action/actions/structure_level_list_of_speakers/add_time.py
  openslides_backend/services/datastore/extended_adapter.py
  setup.cfg
  tests/system/action/structure_level_list_of_speakers/test_add_time.py
Labels: feature, los-extension

#1998 Add `structure_level_id` to `speaker.create`
  openslides_backend/action/actions/speaker/create.py
  tests/system/action/speaker/test_create.py
Labels: feature, los-extension

#1999 Add coupling between speakers and structure levels
  openslides_backend/action/actions/speaker/end_speech.py
  openslides_backend/action/actions/speaker/speak.py
  openslides_backend/action/actions/structure_level_list_of_speakers/__init__.py
  openslides_backend/action/actions/structure_level_list_of_speakers/update.py
  tests/system/action/speaker/test_end_speech.py
  tests/system/action/speaker/test_speak.py
  tests/system/action/structure_level_list_of_speakers/test_update.py
Labels: feature, los-extension

#2000 Add structure level migration
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting_user/history_mixin.py
  openslides_backend/action/actions/meeting_user/mixin.py
  openslides_backend/action/actions/meeting_user/set_data.py
  openslides_backend/action/actions/user/account_json_upload.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/user/merge_together.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/user_mixin.py
  openslides_backend/migrations/migrations/0047_enhance_structure_levels.py
  openslides_backend/models/models.py
  openslides_backend/presenter/get_users.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting_user/test_create.py
  tests/system/action/meeting_user/test_set_data.py
  tests/system/action/meeting_user/test_update.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_save_saml_account.py
  tests/system/action/user/test_update.py
  tests/system/migrations/test_0047_enhance_structure_levels.py
Labels: feature, migration, los-extension

#1816 Some cleanup & typing improvements
  global/meta/models.yml
  openslides_backend/action/action.py
  openslides_backend/action/actions/agenda_item/numbering.py
  openslides_backend/action/actions/group/delete.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/relations/single_relation_handler.py
  openslides_backend/models/models.py
  openslides_backend/permissions/management_levels.py
  openslides_backend/services/auth/adapter.py
  openslides_backend/shared/interfaces/event.py
  openslides_backend/shared/patterns.py
  tests/system/action/agenda_item/test_create.py
  tests/system/relations/test_generic_relations.py
  tests/system/relations/test_relations.py
Labels: clean up

#2001 Add `moderator_notes` to `agenda_item` actions
  global/meta/permission.yml
  openslides_backend/action/actions/agenda_item/create.py
  openslides_backend/action/actions/agenda_item/permission_mixin.py
  openslides_backend/action/actions/agenda_item/update.py
  openslides_backend/permissions/permissions.py
  tests/system/action/agenda_item/test_create.py
  tests/system/action/agenda_item/test_update.py
  tests/system/action/base.py
Labels: feature, los-extension

#2011 I2010 set default_vote_weight to 0.000001 if zero
  openslides_backend/action/actions/meeting/clone.py
  tests/system/action/meeting/test_clone.py
Labels: bug

#2012 I2010 meeting clone default vote weight 2
  openslides_backend/action/actions/meeting/clone.py
  tests/system/action/meeting/test_clone.py
Labels: bug

#2005 Add `mark` html tag to allowed tags
  openslides_backend/shared/util.py
Labels: enhancement

#2007 Add new speech states
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/speaker/create.py
  openslides_backend/action/actions/speaker/mixins.py
  openslides_backend/action/actions/speaker/update.py
  tests/system/action/speaker/test_create.py
  tests/system/action/speaker/test_create_point_of_order.py
  tests/system/action/speaker/test_update.py
Labels: feature, los-extension

#2022 Add `initial_time` as a public field to `structure_level_list_of_speakers.update`
  openslides_backend/action/action.py
  openslides_backend/action/actions/structure_level_list_of_speakers/update.py
  tests/system/action/structure_level_list_of_speakers/test_update.py
Labels: feature

#2030 use argon2 for password hash and verify
  requirements/partial/requirements_production.txt
Labels: critical
