Repository OpenSlides/openslides-backend, pull requests merged in 2023-09, with the labels that each got.

#1891 Update linear sort error messages
  openslides_backend/action/mixins/linear_sort_mixin.py
  tests/system/action/assignment_candidate/test_sort.py
  tests/system/action/chat_group/test_sort.py
  tests/system/action/motion_category/test_sort_motions_in_categories.py
  tests/system/action/motion_comment_section/test_sort.py
  tests/system/action/motion_state/test_sort.py
  tests/system/action/motion_statute_paragraph/test_sort.py
  tests/system/action/motion_submitter/test_sort.py
  tests/system/action/speaker/test_sort.py
Labels: enhancement

#1894 Support point of order speakers in re-add-speaker
  openslides_backend/action/actions/list_of_speakers/re_add_last.py
  tests/system/action/list_of_speakers/test_re_add_last.py
Labels: high, feature

#1898 Revert "Support point of order speakers in re-add-speaker"
  openslides_backend/action/actions/list_of_speakers/re_add_last.py
  tests/system/action/list_of_speakers/test_re_add_last.py
Labels: clean up

#1897 fix amendment_paragraph in rtf migration
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/migrations/migrations/0045_fix_amendment_paragraph.py
  tests/system/migrations/test_0045_fix_amendment_paragraph.py
Labels: bug, critical

#1893 Catch all exceptions during migration
  .github/workflows/continuous_integration.yml
  .github/workflows/create-issue-for-file-updates.yml
  openslides_backend/migrations/migration_handler.py
Labels: enhancement

#1900 migration 0045: update all new fields
  openslides_backend/migrations/migrations/0045_fix_amendment_paragraph.py
  tests/system/migrations/test_0045_fix_amendment_paragraph.py
Labels: bug

#1901 Remove all topic.tag_ids from database
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/migrations/migrations/0046_fix_topic_tag_ids_error.py
  tests/system/migrations/test_0046_fix_topic_tag_ids_error.py
Labels: bug, high, critical

#1908 I1906 migrations replace get-all by filter
  openslides_backend/migrations/migrations/0045_fix_amendment_paragraph.py
  openslides_backend/migrations/migrations/0046_fix_topic_tag_ids_error.py
  tests/system/migrations/test_0046_fix_topic_tag_ids_error.py
Labels: performance

#1895 Make meeting_user actions backend internal
  openslides_backend/action/actions/meeting_user/create.py
  openslides_backend/action/actions/meeting_user/delete.py
  openslides_backend/action/actions/meeting_user/mixin.py
  openslides_backend/action/actions/meeting_user/set_data.py
  openslides_backend/action/actions/meeting_user/update.py
  tests/system/action/meeting_user/test_create.py
  tests/system/action/meeting_user/test_create_delegation.py
  tests/system/action/meeting_user/test_set_data_delegation.py
  tests/system/action/meeting_user/test_update.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
Labels: bug, clean up

#1912 I1896 account.import
  global/meta/models.yml
  openslides_backend/action/action_worker.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/topic/import_.py
  openslides_backend/action/actions/topic/json_upload.py
  openslides_backend/action/actions/user/__init__.py
  openslides_backend/action/actions/user/account_import.py
  openslides_backend/action/actions/user/account_json_upload.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/import_.py
  openslides_backend/action/actions/user/json_upload.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/user_mixin.py
  openslides_backend/action/mixins/import_mixins.py
  openslides_backend/models/models.py
  openslides_backend/presenter/check_database_all.py
  openslides_backend/services/datastore/adapter.py
  openslides_backend/services/datastore/commands.py
  openslides_backend/services/datastore/http_engine.py
  openslides_backend/services/datastore/interface.py
  requirements/export_datastore_commit.sh
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/action/test_action_worker.py
  tests/system/action/topic/test_import.py
  tests/system/action/topic/test_json_upload.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_import.py
  tests/system/action/user/test_json_upload.py
  tests/system/presenter/test_check_database_all.py
  tests/system/presenter/test_export_meeting.py
Labels: enhancement

#1918 Make user.forget_password two-email test safer
  tests/system/action/user/test_forget_password.py
Labels: tests

#1914 Topic json upload rework
  openslides_backend/action/actions/agenda_item/agenda_creation.py
  openslides_backend/action/actions/topic/import_.py
  openslides_backend/action/actions/topic/json_upload.py
  openslides_backend/action/mixins/import_mixins.py
  tests/system/action/topic/test_import.py
  tests/system/action/topic/test_json_upload.py
  tests/system/action/user/test_account_import.py
Labels: enhancement
