Repository OpenSlides/openslides-backend, pull requests merged in 2023-08, with the labels that each got.

#1822 Update GitHub actions
  .github/workflows/continuous_integration.yml
  .github/workflows/create-issue-for-file-updates.yml
Labels: dependencies

#1839 Add test case for participant delete error
  openslides_backend/action/relations/relation_manager.py
  tests/system/action/user/test_delete.py
Labels: bug

#1821 Add saml_id to the account import actions
  openslides_backend/action/actions/user/import_.py
  openslides_backend/action/actions/user/json_upload.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/user_mixin.py
  tests/system/action/user/test_import.py
  tests/system/action/user/test_json_upload.py
  tests/system/action/user/test_update.py
Labels: enhancement

#1808 [feature/remove-template-fields] Move additional model code to mixins
  cli/generate_models.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/replace_projector_id.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/projector/create.py
  openslides_backend/action/actions/projector/update.py
  openslides_backend/models/mixins.py
  openslides_backend/models/models.py
  openslides_backend/presenter/check_mediafile_id.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_update.py
  tests/system/presenter/test_check_database.py
  tests/system/presenter/test_check_database_all.py
Labels: clean up

#1860 change saml_private_key type to text
  global/meta/models.yml
  openslides_backend/models/models.py
Labels: bug

#1866 Add meeting_user_id to user.create action result
  openslides_backend/action/actions/user/create.py
  tests/system/action/user/test_create.py
Labels: bug, high

#1863 Add default to meeting/users_pdf_wlan_encryption
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/presenter/test_check_database_all.py
Labels: feature

#1859 Fix of a problem with calculated user/committee_ids
  openslides_backend/action/relations/user_committee_calculate_handler.py
  tests/system/action/user/test_assign_meetings.py
Labels: bug, high

#1872 Rm required from poll_candidate/user_id
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/action/user/test_delete.py
Labels: high, enhancement

#1861 Fix agenda item update
  openslides_backend/action/actions/agenda_item/update.py
  tests/system/action/agenda_item/test_update.py
Labels: bug

#1875 Add check to forbid self vote delegation
  openslides_backend/action/actions/meeting_user/set_data.py
  tests/system/action/user/test_update.py
Labels: bug

#1817 Catch internal auth password decoding error
  dev/docker-compose.dev.yml
  openslides_backend/http/views/action_view.py
  tests/system/action/test_internal_actions.py
Labels: bug

#1818 Fix reachability of actions in dev mode
  openslides_backend/action/action_handler.py
  tests/system/action/base.py
  tests/system/action/poll/test_vote.py
  tests/system/action/test_internal_actions.py
Labels: enhancement

#1890 Use automation access token in repository_dispatch
  .github/workflows/create-issue-for-file-updates.yml
Labels: clean up
