Repository OpenSlides/openslides-backend, pull requests merged in 2023-06, with the labels that each got.

#1733 new fields and save_saml_account- action for sso
  cli/modelsvalidator/validate.py
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/organization/update.py
  openslides_backend/action/actions/user/__init__.py
  openslides_backend/action/actions/user/create_saml_account.py
  openslides_backend/action/actions/user/save_saml_account.py
  openslides_backend/action/actions/user/update_saml_account.py
  openslides_backend/action/mixins/send_email_mixin.py
  openslides_backend/models/models.py
  requirements/export_datastore_commit.sh
  tests/system/action/organization/test_update.py
  tests/system/action/test_general.py
  tests/system/action/user/test_create_saml_account.py
  tests/system/action/user/test_save_saml_account.py
  tests/system/action/user/test_update_saml_account.py
  tests/system/presenter/test_check_database_all.py
Labels: feature

#1745 Update datastore
  requirements/export_datastore_commit.sh
  tests/system/action/test_general.py
Labels: dependencies

#1744 Issue1742 hide speaker list
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  global/meta/permission.yml
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/projector/create.py
  openslides_backend/action/actions/projector/update.py
  openslides_backend/action/actions/speaker/update.py
  openslides_backend/migrations/migrations/0041_add_list_of_speakers_can_see_to_group_events.py
  openslides_backend/models/models.py
  openslides_backend/permissions/permissions.py
  tests/system/action/group/test_update.py
  tests/system/action/meeting/test_update.py
  tests/system/action/projector/test_create.py
  tests/system/action/projector/test_update.py
  tests/system/action/speaker/test_update.py
  tests/system/migrations/test_0041_add_list_of_speakers_can_see_to_group_events.py
  tests/system/presenter/test_check_database_all.py
  tests/unit/test_permission_helper.py
Labels: migration, enhancement

#1753 Fix bug in projector.update related to is_internal
  openslides_backend/action/actions/projector/update.py
  tests/system/action/projector/test_update.py
Labels: bug

#1739 Template field removal migration
  cli/generate_models.py
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/motion/create.py
  openslides_backend/action/actions/motion/mixins.py
  openslides_backend/action/actions/motion/update.py
  openslides_backend/action/actions/projector/create.py
  openslides_backend/action/actions/projector/update.py
  openslides_backend/migrations/migrations/0042_remove_template_fields.py
  openslides_backend/models/checker.py
  openslides_backend/models/models.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_update.py
  tests/system/action/motion/test_create.py
  tests/system/action/motion/test_create_amendment.py
  tests/system/action/motion/test_create_statute_amendment.py
  tests/system/action/motion/test_update.py
  tests/system/action/projector/test_create.py
  tests/system/action/projector/test_update.py
  tests/system/migrations/conftest.py
  tests/system/migrations/test_0042_remove_template_fields.py
  tests/system/migrations/test_with_sql_dump.py
Labels: high, feature

#1757 Add error type to email action
  openslides_backend/action/actions/user/send_invitation_email.py
  tests/system/action/user/test_send_invitation_email.py
Labels: low, feature

#1755 Generate readable default passwords
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/generate_new_password.py
  openslides_backend/action/actions/user/password_mixin.py
  openslides_backend/action/util/crypto.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_generate_new_password.py
Labels: enhancement

#1759 Add `external_id` to committee, meeting and group
  global/meta/models.yml
  openslides_backend/action/actions/committee/create.py
  openslides_backend/action/actions/committee/update.py
  openslides_backend/action/actions/group/create.py
  openslides_backend/action/actions/group/group_mixin.py
  openslides_backend/action/actions/group/update.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/models/models.py
  tests/system/action/committee/test_create.py
  tests/system/action/committee/test_update.py
  tests/system/action/group/test_create.py
  tests/system/action/group/test_update.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_update.py
  tests/system/action/organization/test_update.py
Labels: feature

#1768 schema must allow None to reset vote forwarding
  openslides_backend/action/actions/user/user_mixin.py
  tests/system/action/user/test_update.py
Labels: bug

#1766 Update motion metadata permissions
  openslides_backend/action/actions/motion/follow_recommendation.py
  openslides_backend/action/actions/motion/reset_recommendation.py
  openslides_backend/action/actions/motion/set_recommendation.py
  openslides_backend/action/actions/motion/update.py
  tests/system/action/motion/test_follow_recommendation.py
  tests/system/action/motion/test_reset_recommendation.py
  tests/system/action/motion/test_set_recommendation.py
  tests/system/action/motion/test_update.py
Labels: bug

#1756 Prevent deletion of group with users
  openslides_backend/action/actions/group/delete.py
  tests/system/action/group/test_delete.py
Labels: enhancement

#1772 Rename default_projector_agenda_item_ids field
  cli/generate_models.py
  global/data/example-data.json
  global/meta/models.yml
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/projector/create.py
  openslides_backend/action/actions/projector/update.py
  openslides_backend/migrations/migrations/0042_remove_template_fields.py
  openslides_backend/models/models.py
  tests/system/migrations/test_0042_remove_template_fields.py
Labels: enhancement

#1764 Add uniqueness checks to `external_id` fields
  global/meta/models.yml
  openslides_backend/action/actions/committee/committee_common_mixin.py
  openslides_backend/action/actions/group/group_mixin.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/mixins/check_unique_name_mixin.py
  openslides_backend/models/models.py
  tests/system/action/committee/test_create.py
  tests/system/action/committee/test_update.py
  tests/system/action/group/test_create.py
  tests/system/action/group/test_update.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_update.py
Labels: enhancement

#1771 I1769 saml problems
  openslides_backend/action/action.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/user/forget_password.py
  openslides_backend/action/actions/user/forget_password_confirm.py
  openslides_backend/action/actions/user/reset_password_to_default.py
  openslides_backend/action/actions/user/save_saml_account.py
  openslides_backend/action/actions/user/set_password.py
  openslides_backend/action/actions/user/set_password_self.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/generics/create.py
  openslides_backend/action/generics/update.py
  openslides_backend/models/fields.py
  tests/system/action/meeting/test_create.py
  tests/system/action/user/test_forget_password.py
  tests/system/action/user/test_forget_password_confirm.py
  tests/system/action/user/test_generate_new_password.py
  tests/system/action/user/test_reset_password_to_default.py
  tests/system/action/user/test_save_saml_account.py
  tests/system/action/user/test_set_password.py
  tests/system/action/user/test_set_password_self.py
  tests/system/action/user/test_update.py
Labels: enhancement

#1779 Add search_for_id_by_external_id presenter and saml_id to user.create
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/search_for_id_by_external_id.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
  tests/system/presenter/test_search_for_id_by_external_id.py
Labels: feature

#1760 Update timestamp fields in motion and motion_workflow
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/action/actions/motion/create_base.py
  openslides_backend/action/actions/motion/mixins.py
  openslides_backend/action/actions/motion/reset_state.py
  openslides_backend/action/actions/motion/set_state.py
  openslides_backend/action/actions/motion/update.py
  openslides_backend/action/actions/motion_state/create.py
  openslides_backend/action/actions/motion_state/update.py
  openslides_backend/action/actions/motion_workflow/create.py
  openslides_backend/migrations/migrations/0043_update_workflow_timestamp.py
  openslides_backend/models/models.py
  tests/system/action/motion/test_create.py
  tests/system/action/motion/test_reset_state.py
  tests/system/action/motion/test_set_state.py
  tests/system/action/motion/test_update.py
  tests/system/action/motion_state/test_create.py
  tests/system/action/motion_state/test_update.py
  tests/system/action/test_action_worker.py
  tests/system/migrations/test_0043_update_workflow_timestamp.py
Labels: feature, migration
