Repository OpenSlides/openslides-backend, pull requests merged in 2024-02, with the labels that each got.

#2173 Fix handling of empty times in `meeting.create`
  openslides_backend/action/actions/meeting/mixins.py
  tests/system/action/meeting/test_create.py
Labels: bug, high

#2175 Fix update past interposed questions
  openslides_backend/action/actions/speaker/update.py
  tests/system/action/speaker/test_update.py
Labels: bug, los-extension

#2178 Use YAML anchors and aliases
  cli/generate_models.py
  cli/validate.py
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/action/meeting/test_import.py
Labels: clean up, enhancement

#2167 Implement email warnings in user imports
  openslides_backend/action/actions/user/base_json_upload.py
  openslides_backend/action/actions/user/participant_json_upload.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug

#2168 Move conditional speaker deletion from user- to meeting_user.delete
  openslides_backend/action/actions/meeting_user/delete.py
  openslides_backend/action/actions/user/conditional_speaker_cascade_mixin.py
  openslides_backend/action/actions/user/delete.py
  tests/system/action/meeting/test_delete.py
  tests/system/action/meeting_user/test_delete.py
  tests/system/action/option/test_delete.py
Labels: enhancement

#2191 Fix committee.import name header
  openslides_backend/action/actions/committee/json_upload.py
  tests/system/action/committee/test_json_upload.py
Labels: bug

#2182 Inject version.txt in via docker build
  Dockerfile
  openslides_backend/version.txt
Labels: enhancement

#2214 Remove los-extension doc hints
  docs/actions/account.json_upload.md
  docs/actions/meeting.update.md
  docs/actions/participant.json_upload.md
  docs/actions/speaker.create.md
  docs/actions/speaker.end_speech.md
  docs/actions/speaker.pause.md
  docs/actions/speaker.speak.md
  docs/actions/speaker.unpause.md
  docs/actions/speaker.update.md
  docs/actions/structure_level.create.md
  docs/actions/structure_level.delete.md
  docs/actions/structure_level.update.md
  docs/actions/structure_level_list_of_speakers.add_time.md
  docs/actions/structure_level_list_of_speakers.create.md
  docs/actions/structure_level_list_of_speakers.delete.md
  docs/actions/structure_level_list_of_speakers.update.md
  docs/actions/user.create.md
  docs/actions/user.update.md
Labels: documentation

#2208 Build group creation into participant import
  openslides_backend/action/actions/user/participant_import.py
  openslides_backend/action/actions/user/participant_json_upload.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: feature

#2211 Allow import for existing users with legacy usernames
  openslides_backend/action/actions/user/base_import.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug, high

#2210 Allow meeting.import only for superadmin
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_import.py
Labels: waiting, enhancement

#2220 Allow initial_time to be changed regardless of speach status
  docs/actions/structure_level_list_of_speakers.update.md
  openslides_backend/action/actions/structure_level_list_of_speakers/update.py
  tests/system/action/structure_level_list_of_speakers/test_update.py
Labels: high, feature, los-extension

#2242 Fix PoO for others
  docs/actions/speaker.create.md
  docs/actions/speaker.update.md
  openslides_backend/action/actions/speaker/create.py
  openslides_backend/action/actions/speaker/mixins.py
  openslides_backend/action/actions/speaker/update.py
  tests/system/action/speaker/test_update.py
Labels: high, feature

#2240 Make SLLoS ignore point-of-order time
  openslides_backend/action/actions/projector_countdown/mixins.py
  openslides_backend/action/actions/speaker/end_speech.py
  openslides_backend/action/actions/speaker/pause.py
  openslides_backend/action/actions/speaker/speak.py
  openslides_backend/action/actions/speaker/unpause.py
  tests/system/action/speaker/test_end_speech.py
  tests/system/action/speaker/test_pause.py
  tests/system/action/speaker/test_speak.py
  tests/system/action/speaker/test_unpause.py
Labels: bug, los-extension

#2244 Stop paused point of order upon start of other speech
  openslides_backend/action/actions/speaker/speak.py
  tests/system/action/speaker/test_speak.py
Labels: bug, los-extension

#2250 Throw custom error for wrong decimal format in imports
  openslides_backend/action/mixins/import_mixins.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug

#2256 Automatically create PRs for commits on staging branches
  .github/workflows/staging-to-main.yml
Labels: enhancement
