Repository OpenSlides/openslides-backend, pull requests merged in 2024-04, with the labels that each got.

#2341 Fix `readd_last` with anonymous interposed questions
  openslides_backend/action/actions/list_of_speakers/re_add_last.py
  tests/system/action/list_of_speakers/test_re_add_last.py
Labels: bug, los-extension

#2359 Fix auth service URL in requirements
  requirements/partial/requirements_packaged_services.txt
Labels: bug, high, dependencies

#2368 saml:add meeting to schema for saml_attribut configuration
  openslides_backend/action/actions/organization/update.py
  tests/system/action/organization/test_update.py
Labels: bug, high, staging

#2295 Add initial data creation
  README.md
  openslides_backend/action/action_handler.py
  openslides_backend/action/mixins/send_email_mixin.py
  openslides_backend/http/application.py
  openslides_backend/main.py
  openslides_backend/shared/env.py
  openslides_backend/shared/interfaces/env.py
  openslides_backend/shared/interfaces/wsgi.py
  openslides_backend/wsgi.py
  setup.cfg
  tests/integration/test_exceptions.py
  tests/system/action/base.py
  tests/system/action/test_create_initial_data.py
  tests/system/action/test_internal_actions.py
  tests/system/base.py
  tests/system/presenter/base.py
  tests/system/util.py
Labels: clean up, feature

#2377 Update `psycopg` to version 3
  dev/docker-compose.dev.yml
  openslides_backend/datastore/shared/postgresql_backend/pg_connection_handler.py
  openslides_backend/datastore/shared/postgresql_backend/schema.sql
  openslides_backend/datastore/shared/postgresql_backend/sql_read_database_backend_service.py
  openslides_backend/datastore/writer/postgresql_backend/sql_database_backend_service.py
  openslides_backend/migrations/core/migraters/event_migrater.py
  openslides_backend/migrations/core/migration_handler.py
  requirements/partial/requirements_production.txt
  setup.cfg
  tests/datastore/fixtures.py
  tests/datastore/migrations/system/conftest.py
  tests/datastore/reader/system/__init__.py
  tests/datastore/reader/system/conftest.py
  tests/datastore/reader/system/test_client.py
  tests/datastore/shared/integration/postgresql_backend/test_pg_connection_handler.py
  tests/datastore/shared/unit/postgresql_backend/test_pg_connection_handler.py
  tests/datastore/shared/unit/postgresql_backend/test_sql_read_database_backend_service.py
  tests/datastore/writer/system/__init__.py
  tests/datastore/writer/system/conftest.py
  tests/datastore/writer/system/truncate_db/test_truncate_db.py
  tests/system/action/user/test_save_saml_account.py
  tests/system/base.py
Labels: dependencies

#2385 Add get_forwarding_committee presenter
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/get_forwarding_committees.py
  tests/system/presenter/test_get_forwarding_committees.py
Labels: feature

#2390 Fix return type
  openslides_backend/action/generics/update.py
Labels: clean up
