Repository OpenSlides/openslides-backend, pull requests merged in 2024-06, with the labels that each got.

#2460 Fix faulty recognition of empty-string names and email in user import
  openslides_backend/action/actions/user/base_json_upload.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug, staging, Becquerel, Zeeman, Michelson

#2464 Add option to project without side effects
  docs/actions/projector.project.md
  openslides_backend/action/actions/projector/project.py
  tests/system/action/projector/test_project.py
Labels: feature, staging

#2476 Removed member_number name generation from user imports
  openslides_backend/action/actions/user/base_json_upload.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_participant_json_upload.py
Labels: enhancement, staging

#2477 Disable delegator restrictions if delegations disabled
  openslides_backend/action/actions/user/delegation_based_restriction_mixin.py
  tests/system/action/motion/test_create.py
  tests/system/action/motion/test_set_support_self.py
  tests/system/action/speaker/test_create.py
  tests/system/action/speaker/test_delete.py
Labels: bug, staging

#1928 I1927 Accelerate poll.stop by reducing locked fields
  .gitmodules
  openslides_backend/action/actions/poll/mixins.py
Labels: high, enhancement

#2489 Remove groupless meeting_users from get_user_related_models response
  openslides_backend/presenter/get_user_related_models.py
  tests/system/presenter/test_get_user_related_models.py
Labels: bug

#2490 Add wiki entry for get_forwarding_committees presenter
  docs/presenters/get_forwarding_committees.md
Labels: documentation, clean up

#2426 Change attribute set is_view_field
  cli/generate_models.py
  global/data/example-data.json
  openslides_backend/models/fields.py
  openslides_backend/models/models.py
Labels: feature

#2504 fix mypy error missing is_in_memory_migration attribute
  openslides_backend/migrations/core/migration_reader.py
Labels: bug

#2500 create small fix for issue 2365 + test
  openslides_backend/action/actions/meeting_user/mixin.py
  tests/system/action/meeting_user/test_set_data_delegation.py
Labels: bug, low

#2505 Adds psycopg3 connection pool and make targets for database
  Makefile
  cli/create_schema.py
  dev/entrypoint.sh
  openslides_backend/database/db_connection_handling.py
  openslides_backend/datastore/shared/postgresql_backend/create_schema.py
  openslides_backend/shared/env.py
  openslides_backend/shared/exceptions.py
Labels: feature
