Repository OpenSlides/openslides-backend, pull requests merged in 2024-11, with the labels that each got.

#2701 Fix empty string translator
  openslides_backend/i18n/translator.py
  tests/unit/test_translator.py
Labels: bug

#2679 More email placeholders
  docs/actions/user.send_invitation_email.md
  openslides_backend/action/actions/user/send_invitation_email.py
  tests/system/action/user/test_send_invitation_email.py
Labels: enhancement, Schrödinger

#2716 Update export_service_commits.sh to new datastore commit
  requirements/export_service_commits.sh
Labels: dependencies

#2698 Case insensitive email matching for forget password
  docs/actions/user.forget_password.md
  openslides_backend/action/actions/user/forget_password.py
  tests/system/action/user/test_forget_password.py
Labels: bug, high

#2726 Bump opentelemetry dependencies update datastore and auth hashes
  requirements/export_service_commits.sh
  requirements/partial/requirements_production.txt
Labels: dependencies

#2622 Check for poll permission correctly
  docs/actions/option.update.md
  docs/actions/poll.anonymize.md
  docs/actions/poll.create.md
  docs/actions/poll.delete.md
  docs/actions/poll.publish.md
  docs/actions/poll.reset.md
  docs/actions/poll.start.md
  docs/actions/poll.stop.md
  docs/actions/poll.update.md
  openslides_backend/action/actions/poll/functions.py
  openslides_backend/action/actions/poll/mixins.py
  tests/system/action/poll/test_create.py
  tests/system/action/poll/test_delete.py
  tests/system/action/poll/test_publish.py
Labels: bug

#2728 Agenda item permission checks for motion.create
  openslides_backend/action/actions/motion/create.py
  tests/system/action/motion/test_create.py
Labels: bug

#2732 beautify docs
  docs/migration_route.md
  docs/presenters/check_database.md
  docs/presenters/check_database_all.md
  docs/presenters/export_meeting.md
  docs/presenters/get_active_users_amount.md
  docs/presenters/get_forwarding_committees.md
  docs/presenters/get_forwarding_meetings.md
  docs/presenters/get_mediafile_context.md
  docs/presenters/get_meetings.md
  docs/presenters/get_user_related_models.md
  docs/presenters/get_user_scope.md
  docs/presenters/get_users.md
  docs/presenters/search_deleted_models.md
  docs/presenters/search_for_id_by_external_id.md
  docs/presenters/search_users.md
Labels: documentation

#2730 Deleted participants stay present in meeting
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/action/actions/meeting_user/delete.py
  openslides_backend/action/actions/user/conditional_speaker_cascade_mixin.py
  openslides_backend/action/actions/user/user_mixins.py
  openslides_backend/migrations/migrations/0062_unset_presence_of_removed_users.py
  tests/system/action/meeting_user/test_delete.py
  tests/system/action/user/test_delete.py
  tests/system/action/user/test_update.py
  tests/system/migrations/test_0062_unset_presence_of_removed_users.py
Labels: bug

#2736 Remove motion import
  docs/actions/motion.import.md
  docs/actions/motion.json_upload.md
  openslides_backend/action/actions/motion/__init__.py
  openslides_backend/action/actions/motion/import_.py
  openslides_backend/action/actions/motion/json_upload.py
  tests/system/action/motion/test_import.py
  tests/system/action/motion/test_json_upload.py
Labels: clean up

#2738 Update debugpy to 1.8.9 and update datastore commit hash
  requirements/export_service_commits.sh
  requirements/partial/requirements_development.txt
Labels: dependencies

#2747 make database check work again
  openslides_backend/presenter/check_database.py
  openslides_backend/shared/export_helper.py
  tests/system/presenter/test_check_database.py
Labels: bug
