Repository OpenSlides/openslides-backend, pull requests merged in 2024-09, with the labels that each got.

#2542 Mostly forbid administrator-less meetings
  docs/actions/committee.json_upload.md
  docs/actions/meeting.clone.md
  docs/actions/meeting.create.md
  docs/actions/meeting.update.md
  docs/actions/participant.import.md
  docs/actions/participant.json_upload.md
  docs/actions/user.delete.md
  docs/actions/user.update.md
  openslides_backend/action/actions/committee/import_.py
  openslides_backend/action/actions/committee/import_mixin.py
  openslides_backend/action/actions/committee/json_upload.py
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/user/base_import.py
  openslides_backend/action/actions/user/delete.py
  openslides_backend/action/actions/user/merge_together.py
  openslides_backend/action/actions/user/participant_common.py
  openslides_backend/action/actions/user/participant_import.py
  openslides_backend/action/actions/user/participant_json_upload.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/user_mixins.py
  tests/system/action/committee/test_import.py
  tests/system/action/committee/test_json_upload.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_update.py
  tests/system/action/test_archived_meeting.py
  tests/system/action/user/test_delete.py
  tests/system/action/user/test_merge_together.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
  tests/system/action/user/test_send_invitation_email.py
  tests/system/action/user/test_update.py
Labels: feature

#2571 Keep the chat_message on deleting meeting_user
  tests/system/action/meeting_user/test_delete.py
Labels: bug

#2606 Make projector.add_to_preview use meeting_mediafile
  openslides_backend/action/actions/projector/add_to_preview.py
  tests/system/action/projector/test_add_to_preview.py
Labels: bug, high, staging

#2611 Fix migration 0054
  openslides_backend/migrations/migrations/0054_split_mediafile_model.py
  tests/system/migrations/test_0054_split_mediafile_model.py
Labels: bug, high, staging

#2616 Prevent user can manage for groups with locked out users
  openslides_backend/action/actions/group/update.py
  tests/system/action/group/test_update.py
Labels: bug, high, Hertz

#2620 Raise proper error for `meeting_id === null` in mediafile.update
  openslides_backend/action/actions/mediafile/update.py
  tests/system/action/mediafile/test_update.py
Labels: bug, staging

#2626 Ensure migration 55 doesn't fail if there's deleted users
  openslides_backend/migrations/migrations/0055_is_active_true_default.py
  tests/system/migrations/test_0055_is_active_true_default.py
Labels: bug, high

#2630 Fix migration 54
  openslides_backend/migrations/migrations/0054_split_mediafile_model.py
  tests/system/migrations/test_0054_split_mediafile_model.py
Labels: bug

#2631 Assign rrenkert for docker in dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#2633 Add migration to fix mistakes from migration 54
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/migrations/migrations/0056_fix_meeting_mediafile_relations.py
  tests/system/migrations/test_0056_fix_meeting_mediafile_relations.py
Labels: bug, high, migration, staging

#2643 change anonymous group weight and name
  docs/actions/group.create.md
  docs/actions/meeting.update.md
  openslides_backend/action/actions/group/create.py
  openslides_backend/action/actions/meeting/update.py
  tests/system/action/meeting/test_update.py
Labels: high, feature, enhancement, Lorentz

#2644 Fix migration 56
  openslides_backend/migrations/migrations/0056_fix_meeting_mediafile_relations.py
Labels: staging
