Repository OpenSlides/openslides-backend, pull requests merged in 2024-03, with the labels that each got.

#2263 Ensure consistent order for `list_of_speakers.re_add_last`
  openslides_backend/action/actions/list_of_speakers/re_add_last.py
  tests/system/action/list_of_speakers/test_re_add_last.py
Labels: bug

#2257 Add merge command
  .github/workflows/commands.yml
Labels: enhancement

#2274 Fix structure level migration test order error
  tests/system/migrations/test_0049_enhance_structure_levels.py
Labels: bug, tests

#2237 Implement readding of interposed questions
  docs/actions/list_of_speakers.re_add_last.md
  openslides_backend/action/actions/list_of_speakers/re_add_last.py
  tests/system/action/list_of_speakers/test_re_add_last.py
Labels: bug, los-extension

#2272 Implement certain preventions for changing active speakers state
  openslides_backend/action/actions/speaker/create.py
  openslides_backend/action/actions/speaker/update.py
  tests/system/action/speaker/test_create.py
  tests/system/action/speaker/test_update.py
Labels: enhancement, staging

#2300 Fix `\update-meta` command
  .github/workflows/commands.yml
Labels: bug

#2301 Fix \update-meta command
  .github/workflows/commands.yml
Labels: bug

#2305 Add colgroup and col to allowed html tags
  openslides_backend/shared/util.py
Labels: feature

#2285 Handle zero default time in projector_countdown.create
  openslides_backend/action/actions/projector_countdown/create.py
  tests/system/action/projector_countdown/test_create.py
Labels: bug

#2279 Add remaining_time to SlLoS.update
  openslides_backend/action/actions/structure_level_list_of_speakers/update.py
  tests/system/action/speaker/test_speak.py
  tests/system/action/structure_level_list_of_speakers/test_update.py
Labels: high, feature, los-extension

#2314 Fix `KeyError` in entitled users calculation
  openslides_backend/action/actions/poll/mixins.py
  tests/system/action/poll/test_stop.py
Labels: bug, high, staging

#2317 Fix fixed list order in tests
  tests/system/action/motion/test_create.py
Labels: bug, tests

#2320 Fix `test_longer_migration`
  tests/system/action/test_migration_route.py
Labels: bug, tests

#2325 Add migration to remove empty structure level remnants
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/migrations/migrations/0052_remove_structure_level_remnants.py
  tests/system/migrations/test_0052_remove_structure_level_remnants.py
  tests/system/migrations/test_with_sql_dump.py
Labels: bug, high, migration

#2322 Change perm for user actions
  docs/actions/meeting.update.md
  docs/actions/user.send_invitation_email.md
  docs/actions/user.set_present.md
  docs/actions/user.toggle_presence_by_number.md
  docs/actions/user.update.md
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/user/generate_new_password.py
  openslides_backend/action/actions/user/reset_password_to_default.py
  openslides_backend/action/actions/user/send_invitation_email.py
  openslides_backend/action/actions/user/set_password.py
  openslides_backend/action/actions/user/toggle_presence_by_number.py
  openslides_backend/shared/mixins/user_scope_mixin.py
  tests/system/action/meeting/test_update.py
  tests/system/action/user/scope_permissions_mixin.py
  tests/system/action/user/test_generate_new_password.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
  tests/system/action/user/test_reset_password_to_default.py
  tests/system/action/user/test_send_invitation_email.py
  tests/system/action/user/test_set_password.py
  tests/system/action/user/test_toggle_presence_by_number.py
  tests/system/action/user/test_update.py
Labels: enhancement

#2328 Fix speaker update KeyError
  openslides_backend/action/actions/structure_level_list_of_speakers/create.py
  tests/system/action/speaker/test_update.py
  tests/system/action/structure_level_list_of_speakers/test_create.py
Labels: bug

#2332 Stop paused speakers in `speaker.speak`
  openslides_backend/action/actions/speaker/speak.py
  tests/system/action/speaker/test_speak.py
Labels: bug, los-extension

#2335 Add user to group in case of saml login
  docs/actions/user.save_saml_account.md
  openslides_backend/action/actions/user/save_saml_account.py
  tests/system/action/user/test_save_saml_account.py
Labels: feature
