Repository OpenSlides/openslides-backend, pull requests merged in 2024-01, with the labels that each got.

#2092 Update `tj-actions/changed-files`
  .github/workflows/create-issue-for-file-updates.yml
Labels: dependencies

#2089 Fix authlib exceptions
  openslides_backend/services/auth/adapter.py
  requirements/export_service_commits.sh
  tests/system/action/base.py
  tests/system/action/poll/base_poll_test.py
  tests/system/action/poll/test_anonymize.py
  tests/system/action/poll/test_create.py
  tests/system/action/poll/test_delete.py
  tests/system/action/poll/test_publish.py
  tests/system/action/poll/test_reset.py
  tests/system/action/poll/test_set_state.py
  tests/system/action/poll/test_start.py
  tests/system/action/poll/test_stop.py
  tests/system/action/poll/test_update.py
  tests/system/action/poll/test_vote.py
  tests/system/action/user/test_forget_password.py
  tests/system/action/user/test_forget_password_confirm.py
  tests/system/action/user/test_generate_new_password.py
  tests/system/action/user/test_reset_password_to_default.py
  tests/system/action/user/test_set_password.py
  tests/system/action/user/test_set_password_self.py
  tests/system/base.py
Labels: bug, clean up

#2079 Add structure level to `speaker.update`
  openslides_backend/action/actions/speaker/create.py
  openslides_backend/action/actions/speaker/mixins.py
  openslides_backend/action/actions/speaker/update.py
  tests/system/action/speaker/test_update.py
Labels: feature, los-extension

#2073 Support truncation of gender list
  openslides_backend/action/actions/organization/update.py
  openslides_backend/services/datastore/adapter.py
  requirements/export_service_commits.sh
  tests/system/action/organization/test_update.py
Labels: bug

#2090 Add vote weight error to account import
  openslides_backend/action/actions/user/account_json_upload.py
  openslides_backend/action/actions/user/participant_json_upload.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug

#2078 Use correct data error index in action workers
  openslides_backend/action/action_worker.py
  openslides_backend/shared/exceptions.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_import.py
  tests/system/action/test_action_worker.py
  tests/system/base.py
  tests/system/presenter/test_check_database_all.py
  tests/system/presenter/test_export_meeting.py
Labels: bug

#2093 Issue2080 Accept ttf-file-extension for mimetype font/sfnt
  openslides_backend/action/actions/mediafile/upload.py
  tests/system/action/mediafile/test_upload.py
Labels: enhancement

#2106 Fix meeting import handling of missing user data
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_import.py
Labels: bug

#2101 Add new defaults to motion_state
  global/data/example-data.json
  global/data/initial-data.json
  global/meta/models.yml
  openslides_backend/migrations/migrations/0047_add_workflow_state_boolean_defaults.py
  openslides_backend/models/models.py
  tests/system/migrations/test_0047_add_workflow_state_boolean_defaults.py
  tests/system/presenter/test_check_database_all.py
Labels: migration, enhancement

#2110 Fix meeting.clone set active code
  global/data/example-data.json
  global/data/initial-data.json
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/migrations/migrations/0048_fix_broken_meeting_clones.py
  tests/system/action/meeting/test_clone.py
  tests/system/migrations/test_0048_fix_broken_meeting_clones.py
Labels: bug, migration

#2103 Fix interposed questions
  global/meta/models.yml
  openslides_backend/action/actions/speaker/create.py
  openslides_backend/action/actions/speaker/end_speech.py
  openslides_backend/action/actions/speaker/mixins.py
  openslides_backend/action/actions/speaker/pause.py
  openslides_backend/action/actions/speaker/speak.py
  openslides_backend/action/actions/speaker/speech_state.py
  openslides_backend/action/actions/speaker/unpause.py
  openslides_backend/action/actions/speaker/update.py
  openslides_backend/action/actions/structure_level_list_of_speakers/update.py
  openslides_backend/models/models.py
  tests/system/action/speaker/test_create.py
  tests/system/action/speaker/test_end_speech.py
  tests/system/action/speaker/test_pause.py
  tests/system/action/speaker/test_speak.py
  tests/system/action/speaker/test_unpause.py
  tests/system/action/speaker/test_update.py
Labels: bug, los-extension

#2115 Fix user csv import username generation
  openslides_backend/action/actions/user/base_json_upload.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug, high

#2132 Improve models check
  Makefile
  cli/generate_models.py
  openslides_backend/models/models.py
Labels: enhancement

#2128 Add `equal_fields` to `motion/supporter_meeting_user_ids`
  global/meta/models.yml
  openslides_backend/models/models.py
  tests/system/action/motion/test_update.py
Labels: bug

#2125 Allow interposed question while speaker is paused
  openslides_backend/action/actions/speaker/speak.py
  tests/system/action/speaker/test_speak.py
Labels: bug, los-extension

#2139 End interposed questions with their parents
  openslides_backend/action/actions/speaker/end_speech.py
  tests/system/action/speaker/test_end_speech.py
Labels: bug, los-extension

#2142 Add overhang time only to already present structure levels
  openslides_backend/action/actions/structure_level_list_of_speakers/add_time.py
  tests/system/action/structure_level_list_of_speakers/test_add_time.py
Labels: bug, los-extension

#2129 Add new motion fields & fix `can_manage_metadata`
  global/meta/models.yml
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/motion/update.py
  openslides_backend/models/models.py
  tests/system/action/motion/test_update.py
Labels: bug, feature

#1878 Committee import
  global/meta/models.yml
  openslides_backend/action/actions/committee/__init__.py
  openslides_backend/action/actions/committee/import_.py
  openslides_backend/action/actions/committee/json_upload.py
  openslides_backend/action/actions/meeting/create.py
  openslides_backend/action/actions/meeting/mixins.py
  openslides_backend/action/actions/topic/import_.py
  openslides_backend/action/actions/topic/json_upload.py
  openslides_backend/action/actions/user/base_import.py
  openslides_backend/action/actions/user/base_json_upload.py
  openslides_backend/action/actions/user/participant_common.py
  openslides_backend/action/actions/user/participant_import.py
  openslides_backend/action/mixins/import_mixins.py
  openslides_backend/models/models.py
  tests/system/action/committee/test_import.py
  tests/system/action/committee/test_json_upload.py
  tests/system/action/topic/test_json_upload.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_participant_import.py
  tests/system/base.py
  tests/system/migrations/test_0037_remove_user_projections.py
Labels: feature

#2148 Make participant import create structure levels
  openslides_backend/action/actions/user/base_import.py
  openslides_backend/action/actions/user/participant_import.py
  openslides_backend/action/actions/user/participant_json_upload.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: feature, los-extension

#2154 Allow speech state switch from intervention
  openslides_backend/action/actions/speaker/update.py
  tests/system/action/speaker/test_update.py
Labels: bug, los-extension
