Repository OpenSlides/openslides-backend, pull requests merged in 2024-10, with the labels that each got.

#2657 Ensure speaker.delete only resets projector countdown with active speakers
  docs/actions/speaker.delete.md
  openslides_backend/action/actions/speaker/delete.py
  tests/system/action/speaker/test_delete.py
Labels: bug, high, staging

#2662 Fix assignment_candidate cascade deletion error
  docs/actions/assignment_candidate.delete.md
  openslides_backend/action/actions/assignment_candidate/delete.py
  tests/system/action/assignment/test_delete.py
  tests/system/action/user/test_merge_together.py
Labels: bug

#2678 make meeting clone with gender in user possible again
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/shared/export_helper.py
  tests/system/action/meeting/test_clone.py
Labels: bug, staging

#2683 Fix action worker test
  tests/system/action/test_action_worker.py
Labels: high, tests

#2684 fix participant import with meeting admin
  openslides_backend/action/actions/user/participant_json_upload.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug, staging

#2689 participant import error with gender and meeting admin
  openslides_backend/action/actions/user/participant_import.py
  openslides_backend/action/actions/user/participant_json_upload.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug, staging

#2707 Fix mismatch of perm check of get-forwarding-meetings
  openslides_backend/presenter/get_forwarding_meetings.py
  tests/system/presenter/test_get_forwarding_meetings.py
Labels: bug
