Repository OpenSlides/openslides-backend, pull requests merged in 2024-05, with the labels that each got.

#2403 Fix LoS countdowns on speaker deletion
  openslides_backend/action/actions/speaker/delete.py
  tests/system/action/speaker/test_delete.py
Labels: bug, high, staging

#2432 Add otel setup analogous to main repo
  Makefile
  dev/dc.otel.yml
  dev/docker-compose.dev.yml
  dev/otel-collector-config.yml
  openslides_backend/shared/otel.py
Labels: enhancement

#2442 Fix html.parser error for empty html, add skipped file import
  openslides_backend/shared/html.py
  tests/system/action/meeting/test_import.py
Labels: bug

#2434 Fix CheckMediafileId presenter for anonymous user
  openslides_backend/presenter/check_mediafile_id.py
Labels: bug

#2439 Allow additional submitters update with CAN_MANAGE_METADATA
  docs/actions/motion.update.md
  openslides_backend/action/actions/motion/update.py
  openslides_backend/presenter/get_forwarding_committees.py
  tests/system/action/motion/test_update.py
Labels: bug, high

#2452 Allow clearing of member_number
  openslides_backend/action/actions/user/user_mixins.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
Labels: bug, high
