Repository OpenSlides/openslides-backend, pull requests merged in 2024-12, with the labels that each got.

#2748 Translate public group name
  openslides_backend/action/actions/meeting/update.py
  tests/system/action/base.py
  tests/system/action/meeting/test_settings.py
  tests/system/action/meeting/test_update.py
  tests/system/action/test_action_command_format.py
Labels: bug

#2745 saml-meeting-mapping: allow boolean attributes and vote weight as string
  docs/actions/organization.update.md
  docs/actions/user.save_saml_account.md
  openslides_backend/action/actions/organization/update.py
  openslides_backend/action/actions/user/save_saml_account.py
  openslides_backend/models/fields.py
  tests/system/action/organization/test_update.py
  tests/system/action/user/test_save_saml_account.py
Labels: bug

#2751 Put all candidates on the LOS when setting phase to voting dependant
  docs/actions/assignment.update.md
  openslides_backend/action/actions/assignment/create_update_delete.py
  openslides_backend/action/mixins/singular_action_mixin.py
  tests/system/action/assignment/test_update.py
Labels: high, feature

#2752 Kill all sessions of user set to inactive
  openslides_backend/action/actions/user/update.py
  openslides_backend/services/auth/adapter.py
  openslides_backend/services/auth/interface.py
  requirements/export_service_commits.sh
  tests/system/action/user/test_update.py
Labels: enhancement

#2766 Allow submitter ids and additional submitter on motion create
  docs/actions/motion.create.md
  openslides_backend/action/actions/motion/create.py
  tests/system/action/motion/test_create.py
Labels: bug

#2772 Forbid unreasonable vote amounts
  docs/actions/poll.create.md
  docs/actions/poll.update.md
  openslides_backend/action/actions/poll/create.py
  openslides_backend/action/actions/poll/mixins.py
  openslides_backend/action/actions/poll/update.py
  tests/system/action/option/test_update.py
  tests/system/action/poll/test_create.py
  tests/system/action/poll/test_update.py
Labels: bug

#2768 Ignore assignment candidates already on list of speakers on phase to voting
  docs/actions/assignment.update.md
  openslides_backend/action/actions/assignment/create_update_delete.py
  tests/system/action/assignment/test_update.py
Labels: bug
