Repository OpenSlides/openslides-backend, pull requests merged in 2024-08, with the labels that each got.

#2539 Improve check_delegator_restriction function
  openslides_backend/action/mixins/delegation_based_restriction_mixin.py
Labels: enhancement

#2531 Implement locking out participants
  docs/actions/meeting_user.create.md
  docs/actions/meeting_user.update.md
  docs/actions/participant.json_upload.md
  docs/actions/user.create.md
  docs/actions/user.merge_together.md
  docs/actions/user.update.md
  docs/presenters/get_user_related_models.md
  openslides_backend/action/actions/meeting_user/create.py
  openslides_backend/action/actions/meeting_user/mixin.py
  openslides_backend/action/actions/meeting_user/set_data.py
  openslides_backend/action/actions/meeting_user/update.py
  openslides_backend/action/actions/user/create.py
  openslides_backend/action/actions/user/create_update_permissions_mixin.py
  openslides_backend/action/actions/user/participant_common.py
  openslides_backend/action/actions/user/participant_import.py
  openslides_backend/action/actions/user/participant_json_upload.py
  openslides_backend/action/actions/user/update.py
  openslides_backend/action/actions/user/user_mixins.py
  openslides_backend/permissions/permission_helper.py
  openslides_backend/presenter/get_user_related_models.py
  tests/system/action/base.py
  tests/system/action/base_motion_meeting_user_create_test.py
  tests/system/action/meeting_user/test_create.py
  tests/system/action/meeting_user/test_update.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_merge_together.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
  tests/system/action/user/test_update.py
  tests/system/presenter/test_get_user_related_models.py
Labels: high, feature, Zeeman

#2540 Forbid committee admins from cloning foreign non-template meetings
  docs/actions/meeting.clone.md
  openslides_backend/action/actions/meeting/clone.py
  tests/system/action/meeting/test_clone.py
Labels: bug, high

#2567 remove server time
  docs/presenters/servertime.md
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/server_time.py
  tests/system/presenter/test_server_time.py
Labels: clean up

#2569 removed check media file id and its auth method
  docs/Presenters-Overview.md
  docs/presenters/check_mediafile_id.md
  openslides_backend/presenter/__init__.py
  openslides_backend/presenter/base.py
  openslides_backend/presenter/check_mediafile_id.py
  openslides_backend/presenter/presenter.py
  openslides_backend/services/auth/adapter.py
  openslides_backend/services/auth/interface.py
  tests/system/presenter/test_check_mediafile_id.py
  tests/unit/test_presenter.py
Labels: clean up

#2568 Update clone perms: allow only template or same committee
  docs/actions/meeting.clone.md
  openslides_backend/action/actions/meeting/clone.py
  tests/system/action/meeting/test_clone.py
Labels: enhancement, staging

#2586 Add `member_number` to search users presenter
  docs/presenters/search_users.md
  openslides_backend/presenter/search_users.py
  tests/system/presenter/test_search_users.py
Labels: enhancement
