Repository OpenSlides/openslides-backend, pull requests merged in 2025-07, with the labels that each got.

#2999 Add superadmin self-inactive setting check in user imports
  docs/actions/participant.json_upload.md
  openslides_backend/action/actions/user/base_json_upload.py
  tests/system/action/user/test_account_json_upload.py
  tests/system/action/user/test_participant_json_upload.py
Labels: bug, documentation

#3014 Fix motion forward with attachments
  openslides_backend/action/actions/mediafile/duplicate_to_another_meeting.py
  openslides_backend/action/actions/motion/base_create_forwarded.py
  tests/system/action/motion/test_create_forwarded.py
Labels: bug, clean up

#3016 Refactor permission_helper methods
  openslides_backend/action/actions/committee/committee_common_mixin.py
  openslides_backend/action/actions/committee/create.py
  openslides_backend/action/actions/committee/delete.py
  openslides_backend/action/actions/committee/update.py
  openslides_backend/action/actions/meeting/archive.py
  openslides_backend/action/actions/meeting/mixins.py
  openslides_backend/action/actions/meeting/update.py
  openslides_backend/action/actions/user/assign_meetings.py
  openslides_backend/action/actions/user/set_present.py
  openslides_backend/action/actions/user/toggle_presence_by_number.py
  openslides_backend/permissions/permission_helper.py
  openslides_backend/presenter/search_users.py
  openslides_backend/shared/mixins/user_create_update_permissions_mixin.py
  openslides_backend/shared/mixins/user_scope_mixin.py
Labels: clean up

#3025 Update unique mediafile title suffixes
  openslides_backend/action/actions/mediafile/duplicate_to_another_meeting.py
  tests/system/action/motion/test_create_forwarded.py
Labels: bug, staging

#3065 Make meeting is_admin check work for committee admins
  openslides_backend/permissions/permission_helper.py
  tests/system/action/group/test_create.py
  tests/system/action/group/test_update.py
  tests/system/action/meeting/test_update.py
Labels: bug
