Repository OpenSlides/openslides-backend, pull requests merged in 2025-05, with the labels that each got.

#2923 Extend user scope with archived meetings for cmo and oml
  docs/presenters/get_user_scope.md
  openslides_backend/action/actions/user/user_mixins.py
  openslides_backend/action/mixins/archived_meeting_check_mixin.py
  openslides_backend/presenter/get_user_scope.py
  openslides_backend/shared/mixins/user_create_update_permissions_mixin.py
  openslides_backend/shared/mixins/user_scope_mixin.py
  tests/system/action/user/test_update.py
  tests/system/presenter/test_get_user_scope.py
Labels: feature

#2919 Fix permissions check for meeting.clone in mixin
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/delete.py
  openslides_backend/action/actions/meeting/mixins.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_delete.py
Labels: bug

#2951 Make poll delete inform vote service on success
  openslides_backend/action/actions/poll/delete.py
  tests/system/action/poll/test_delete.py
  tests/system/action/poll/test_stop.py
Labels: bug

#2950 Lengthen migrate thread join timeout
  openslides_backend/migrations/migration_handler.py
Labels: bug

#2955 Remove statute_paragraph code
  openslides_backend/action/actions/motion/base_create_forwarded.py
  openslides_backend/action/actions/motion/create_forwarded_amendment.py
Labels: clean up

#2956 Fix committee CSV import creates tags several times
  docs/actions/committee.import.md
  openslides_backend/action/actions/committee/import_.py
  openslides_backend/action/actions/committee/json_upload.py
  tests/system/action/committee/test_import.py
  tests/system/action/committee/test_json_upload.py
Labels: bug
