Repository OpenSlides/openslides-backend, pull requests merged in 2025-06, with the labels that each got.

#2976 Fix gender field in user imports
  openslides_backend/action/actions/user/base_import.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
Labels: bug, staging

#2979 Ensure using multiple home committees works
  openslides_backend/action/actions/user/base_json_upload.py
  tests/system/action/user/test_account_import.py
  tests/system/action/user/test_account_json_upload.py
Labels: bug, staging

#2949 Allow forwarding motions with attachments
  docs/actions/mediafile.duplicate_to_another_meeting.md
  docs/actions/motion.create_forwarded.md
  docs/actions/motion.create_forwarded_amendment.md
  openslides_backend/action/actions/mediafile/duplicate_to_another_meeting.py
  openslides_backend/action/actions/motion/base_create_forwarded.py
  openslides_backend/action/actions/motion/create_forwarded.py
  openslides_backend/action/actions/motion/create_forwarded_amendment.py
  tests/system/action/motion/test_create_forwarded.py
Labels: feature, Onnes

#3001 Optimize committee update
  openslides_backend/action/actions/committee/update.py
Labels: clean up
