Repository OpenSlides/openslides-backend, pull requests merged in 2025-03, with the labels that each got.

#2744 Allow the orgaadmin to do more
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/mixins.py
  openslides_backend/action/mixins/motion_meeting_user_create.py
  openslides_backend/permissions/permission_helper.py
  openslides_backend/shared/mixins/user_create_update_permissions_mixin.py
  tests/system/action/agenda_item/test_assign.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_delete.py
  tests/system/action/meeting/test_update.py
  tests/system/action/motion/test_create.py
  tests/system/action/test_permissions.py
  tests/system/action/user/test_create.py
  tests/system/action/user/test_update.py
Labels: feature

#2875 Update pygments types
  openslides_backend/action/actions/mediafile/upload.py
  requirements/export_service_commits.sh
  requirements/partial/requirements_development.txt
Labels: dependencies, python

#2877 Italien translations
  openslides_backend/i18n/messages/it.po
Labels: translation

#2890 Forbid setting woff2 as font
  openslides_backend/action/actions/meeting/set_font.py
Labels: bug

#2894 Improve motion_category weight generation
  docs/actions/motion_category.create.md
  openslides_backend/action/actions/motion_category/create_update_delete.py
  tests/system/action/motion_category/test_create.py
Labels: bug, waiting

#2900 Update translations
  openslides_backend/i18n/messages/cs.po
  openslides_backend/i18n/messages/de.po
  openslides_backend/i18n/messages/es.po
  openslides_backend/i18n/messages/fr.po
  openslides_backend/i18n/messages/it.po
  openslides_backend/i18n/messages/ru.po
  openslides_backend/i18n/messages/template-en.pot
Labels: staging

#2903 Use attribute whitelist for HTML sanitization
  openslides_backend/shared/util.py
Labels: bug, high, staging

#2910 Allow assign meetings for committee admins
  docs/actions/user.assign_meetings.md
  openslides_backend/action/actions/user/assign_meetings.py
  tests/system/action/user/test_assign_meetings.py
Labels: feature

#2912 Update opentelemetry-dependencies
  requirements/export_service_commits.sh
  requirements/partial/requirements_production.txt
Labels: dependencies

#2914 Update csv import warning message
  openslides_backend/action/actions/user/participant_json_upload.py
  tests/system/action/user/test_participant_import.py
  tests/system/action/user/test_participant_json_upload.py
Labels: enhancement

#2917 Prevent archiving of meeting with running processes
  docs/actions/meeting.archive.md
  openslides_backend/action/actions/meeting/archive.py
  tests/system/action/meeting/test_archive.py
Labels: enhancement
