Repository OpenSlides/openslides-backend, pull requests merged in 2025-01, with the labels that each got.

#2786 Upgrade mypy dependency
  openslides_backend/action/actions/speaker/update.py
  requirements/partial/requirements_development.txt
Labels: dependencies, python

#2787 Upgrade opentelemetry debugpy fastjsonschema and hashes
  requirements/export_service_commits.sh
  requirements/partial/requirements_development.txt
  requirements/partial/requirements_production.txt
Labels: dependencies, python

#2779 Add foreign delegation removal from user.update_self
  docs/actions/user.update_self.md
  openslides_backend/action/actions/user/update_self.py
  tests/system/action/user/test_update_self.py
Labels: feature, Hertz

#2792 Fix merge for users without meetings
  openslides_backend/action/actions/user/merge_together.py
  tests/system/action/user/test_merge_together.py
Labels: bug

#2794 Edit merge settings of example-data workflow states
  data/example-data.json
Labels: enhancement

#2793 Fix merge for saml users in case of password changing rights
  docs/actions/user.merge_together.md
  openslides_backend/action/actions/user/merge_together.py
  tests/system/action/user/test_merge_together.py
Labels: bug

#2800 accurize decimal description in documentation
  docs/actions/preface_special_imports.md
Labels: documentation

#2791 Fix meeting.clone list election behaviour
  openslides_backend/shared/export_helper.py
  tests/system/action/base.py
  tests/system/action/meeting/test_clone.py
Labels: bug, staging

#2805 Update datastore hash
  requirements/export_service_commits.sh
Labels: dependencies

#2813 Update service commits
  requirements/export_service_commits.sh
Labels: dependencies

#2820 Delete all moderator notes in agenda items
  data/example-data.json
  data/initial-data.json
  openslides_backend/migrations/migrations/0063_delete_empty_moderator_notes.py
  tests/system/migrations/test_0063_delete_empty_moderator_notes.py
Labels: bug, high
