Repository OpenSlides/openslides-backend, pull requests merged in 2025-02, with the labels that each got.

#2816 Fix meeting import spelling error
  docs/actions/meeting.import.md
  openslides_backend/action/actions/meeting/import_.py
  tests/system/action/meeting/test_import.py
Labels: bug

#2831 Bump black from 24.10.0 to 25.1.0 in /requirements/partial
  openslides_backend/action/action_handler.py
  openslides_backend/action/actions/agenda_item/agenda_creation.py
  openslides_backend/action/mixins/import_mixins.py
  requirements/partial/requirements_development.txt
  tests/system/action/user/test_merge_together.py
Labels: dependencies

#2844 Fix tests after vote service update
  tests/system/action/poll/poll_test_mixin.py
  tests/system/action/poll/test_publish.py
  tests/system/action/poll/test_reset.py
  tests/system/action/poll/test_start.py
  tests/system/action/poll/test_stop.py
  tests/system/action/poll/test_vote.py
Labels: tests

#2854 Accept more types for condition check
  docs/actions/user.save_saml_account.md
  openslides_backend/action/actions/user/save_saml_account.py
  tests/system/action/user/test_save_saml_account.py
Labels: bug, feature

#2855 Make meeting/external_id unique in org
  docs/actions/meeting.clone.md
  docs/actions/meeting.create.md
  docs/actions/meeting.import.md
  docs/actions/meeting.update.md
  openslides_backend/action/actions/meeting/clone.py
  openslides_backend/action/actions/meeting/import_.py
  openslides_backend/action/actions/meeting/mixins.py
  openslides_backend/action/actions/meeting/update.py
  tests/system/action/meeting/test_clone.py
  tests/system/action/meeting/test_create.py
  tests/system/action/meeting/test_import.py
  tests/system/action/meeting/test_update.py
Labels: bug

#2862 Bump simplejson from 3.19.3 to 3.20.1 in /requirements/partial
  requirements/export_service_commits.sh
  requirements/partial/requirements_production.txt
Labels: dependencies, python

#2863 Remove 'Group not found' error from user.assign_meetings
  docs/actions/user.assign_meetings.md
  openslides_backend/action/actions/user/assign_meetings.py
  tests/system/action/user/test_assign_meetings.py
Labels: enhancement
